"""
FWA Metadata Gazetteer

Loads and queries the stream_metadata.pickle file generated by metadata_builder.py
to provide fast waterbody name lookups for regulation linking.

Also loads enriched KML points (unnamed lakes, future landmarks) for additional matching.
"""

import pickle
import json
from pathlib import Path
from typing import List, Dict, Optional, Any, Set
from dataclasses import dataclass
from enum import Enum
import logging

from ..graph.metadata_builder import FeatureType

logger = logging.getLogger(__name__)


@dataclass
class FWAFeature:
    """
    Represents a feature from the FWA (Freshwater Atlas) database.
    """

    fwa_id: str
    geometry_type: str  # "polygon", "multilinestring", "point"
    zones: List[str]  # All zones this feature appears in
    feature_type: Optional[FeatureType] = None
    gnis_name: Optional[str] = None
    gnis_id: Optional[str] = None
    gnis_name_2: Optional[str] = None
    gnis_id_2: Optional[str] = None
    fwa_watershed_code: Optional[str] = None
    blue_line_key: Optional[str] = None  # Added natively to the dataclass!
    mgmt_units: Optional[List[str]] = None
    waterbody_key: Optional[str] = None
    matched_via: Optional[str] = None

    def __eq__(self, other):
        if not isinstance(other, FWAFeature):
            return False
        return self.fwa_id == other.fwa_id

    def __hash__(self):
        return hash(self.fwa_id)


class FWAUnpickler(pickle.Unpickler):
    """
    Custom unpickler to handle the namespace shift.
    Redirects __main__.FeatureType to our correctly imported FeatureType.
    """

    def find_class(self, module, name):
        if name == "FeatureType" and module == "__main__":
            from ..graph.metadata_builder import FeatureType

            return FeatureType
        return super().find_class(module, name)


class MetadataGazetteer:
    """
    Gazetteer backed by stream_metadata.pickle file.
    Uses FeatureType Enum members as keys for the internal metadata dictionary.
    """

    def __init__(self, metadata_path: Path):
        """
        Initialize gazetteer from metadata pickle file.
        """
        self.metadata_path = metadata_path
        self.metadata: Dict[Any, Any] = {}
        self.name_index: Dict[str, List[FWAFeature]] = {}

        self._load_metadata()
        self._build_index()

    def _load_metadata(self):
        """Load metadata from pickle file."""
        logger.info(f"Loading FWA metadata from: {self.metadata_path}")

        with open(self.metadata_path, "rb") as f:
            self.metadata = FWAUnpickler(f).load()

        # Log summary using Enum keys
        logger.info(f"  Zones: {len(self.metadata.get('zone_metadata', {}))}")
        logger.info(f"  Streams: {len(self.metadata.get(FeatureType.STREAM, {})):,}")
        logger.info(f"  Lakes: {len(self.metadata.get(FeatureType.LAKE, {})):,}")
        logger.info(f"  Wetlands: {len(self.metadata.get(FeatureType.WETLAND, {})):,}")
        logger.info(f"  Manmade: {len(self.metadata.get(FeatureType.MANMADE, {})):,}")

    def _build_feature(
        self,
        fwa_id: str,
        feature_data: Dict[str, Any],
        feature_type: FeatureType,
        matched_via: Optional[str] = None,
    ) -> FWAFeature:
        """Centralized factory for creating FWAFeature objects uniformly."""
        # Determine geometry type
        geometry_type = (
            "multilinestring" if feature_type == FeatureType.STREAM else "polygon"
        )

        # Determine waterbody_key (polygons fallback to their fwa_id/poly_id if missing)
        waterbody_key = feature_data.get("waterbody_key")
        if waterbody_key is None and feature_type != FeatureType.STREAM:
            waterbody_key = fwa_id

        # Normalize zones
        zones = feature_data.get("zones")
        if not zones:
            zones = ["Unknown"]

        # Safely parse GNIS names
        gnis_name = feature_data.get("gnis_name")
        if isinstance(gnis_name, str):
            gnis_name = gnis_name.strip() or None

        gnis_name_2 = feature_data.get("gnis_name_2")
        if isinstance(gnis_name_2, str):
            gnis_name_2 = gnis_name_2.strip() or None

        # Smart GNIS ID handling: fallback to gnis_id_2 if primary is missing
        gnis_id = feature_data.get("gnis_id")
        gnis_id_2 = feature_data.get("gnis_id_2")
        final_gnis_id = gnis_id if gnis_id else gnis_id_2

        return FWAFeature(
            fwa_id=str(fwa_id),
            geometry_type=geometry_type,
            zones=zones,
            feature_type=feature_type,
            gnis_name=gnis_name,
            gnis_id=final_gnis_id,
            gnis_name_2=gnis_name_2,
            gnis_id_2=gnis_id_2,
            fwa_watershed_code=feature_data.get("fwa_watershed_code"),
            blue_line_key=feature_data.get("blue_line_key"),
            mgmt_units=feature_data.get("mgmt_units", []),
            waterbody_key=str(waterbody_key) if waterbody_key is not None else None,
            matched_via=matched_via,
        )

    def _build_index(self):
        """Build name-based index from metadata."""
        logger.info("Building name index...")

        # Index streams by gnis_name
        for linear_id, stream_data in self.metadata.get(FeatureType.STREAM, {}).items():
            gnis_name = stream_data.get("gnis_name", "")
            if isinstance(gnis_name, str) and gnis_name.strip():
                feature = self._build_feature(
                    linear_id, stream_data, FeatureType.STREAM
                )
                normalized = self._normalize_for_index(gnis_name)
                self.name_index.setdefault(normalized, []).append(feature)

        # Index lakes, wetlands, manmade by gnis_name and gnis_name_2
        for ftype_enum in [FeatureType.LAKE, FeatureType.WETLAND, FeatureType.MANMADE]:
            for poly_id, feature_data in self.metadata.get(ftype_enum, {}).items():
                gnis_name = feature_data.get("gnis_name", "")
                gnis_name_2 = feature_data.get("gnis_name_2", "")

                if isinstance(gnis_name, str) and gnis_name.strip():
                    feature = self._build_feature(poly_id, feature_data, ftype_enum)
                    normalized = self._normalize_for_index(gnis_name)
                    self.name_index.setdefault(normalized, []).append(feature)

                if isinstance(gnis_name_2, str) and gnis_name_2.strip():
                    feature_2 = self._build_feature(poly_id, feature_data, ftype_enum)
                    normalized_2 = self._normalize_for_index(gnis_name_2)
                    self.name_index.setdefault(normalized_2, []).append(feature_2)

        logger.info(f"  Indexed {len(self.name_index):,} unique waterbody names")

    def _normalize_for_index(self, name: str) -> str:
        """Normalize name for indexing (title case, stripped)."""
        return name.strip().title()

    def search(self, name: str, region: Optional[str] = None) -> List[FWAFeature]:
        """Search for FWA features by name."""
        normalized = self._normalize_for_index(name)
        matches = self.name_index.get(normalized, [])
        if region:
            matches = [f for f in matches if region in f.zones]
        return matches

    def get_stream_metadata(self, linear_feature_id: str) -> Optional[Dict]:
        """Get full metadata dict for a stream."""
        return self.metadata.get(FeatureType.STREAM, {}).get(linear_feature_id)

    def get_valid_stream_ids(self) -> Set[str]:
        """Get set of all valid linear_feature_ids."""
        return set(self.metadata.get(FeatureType.STREAM, {}).keys())

    def get_stream_by_id(self, linear_feature_id: str) -> Optional[FWAFeature]:
        """Get stream feature as FWAFeature by linear_feature_id."""
        metadata = self.get_stream_metadata(linear_feature_id)
        if not metadata:
            return None
        return self._build_feature(linear_feature_id, metadata, FeatureType.STREAM)

    def get_polygon_metadata(
        self, waterbody_key: str, feature_type: Optional[FeatureType] = None
    ) -> Optional[Dict]:
        """Get full metadata for a polygon feature."""
        if feature_type:
            return self.metadata.get(feature_type, {}).get(waterbody_key)

        for ftype in [FeatureType.LAKE, FeatureType.WETLAND, FeatureType.MANMADE]:
            result = self.metadata.get(ftype, {}).get(waterbody_key)
            if result:
                return result
        return None

    def get_zone_metadata(self, zone_number: str) -> Optional[Dict]:
        """Get metadata for a specific zone."""
        return self.metadata.get("zone_metadata", {}).get(zone_number)

    def get_features_in_zone(
        self, zone_number: str, feature_type: FeatureType = FeatureType.STREAM
    ) -> List[Dict]:
        """Get all features in a specific zone."""
        features = []
        for metadata in self.metadata.get(feature_type, {}).values():
            if zone_number in metadata.get("zones", []):
                features.append(metadata)
        return features

    def get_waterbody_by_key(self, waterbody_key: str) -> List[FWAFeature]:
        """Get ALL FWA features with the given waterbody_key."""
        features = []
        for ftype_enum in [FeatureType.LAKE, FeatureType.WETLAND, FeatureType.MANMADE]:
            for poly_id, feature_data in self.metadata.get(ftype_enum, {}).items():
                if str(feature_data.get("waterbody_key", "")) == str(waterbody_key):
                    features.append(
                        self._build_feature(poly_id, feature_data, ftype_enum)
                    )
        return features

    def get_polygon_by_id(self, poly_id: str) -> Optional[FWAFeature]:
        """Get a specific polygon by WATERBODY_POLY_ID."""
        for ftype_enum in [FeatureType.LAKE, FeatureType.WETLAND, FeatureType.MANMADE]:
            feature_data = self.metadata.get(ftype_enum, {}).get(poly_id)
            if feature_data:
                return self._build_feature(poly_id, feature_data, ftype_enum)
        return None

    def search_by_gnis_id(self, gnis_id: str) -> List[FWAFeature]:
        """Search for all features with a specific GNIS ID."""
        features = []
        for lid, meta in self.metadata.get(FeatureType.STREAM, {}).items():
            if str(meta.get("gnis_id")) == str(gnis_id):
                features.append(self.get_stream_by_id(lid))
        for ftype in [FeatureType.LAKE, FeatureType.WETLAND, FeatureType.MANMADE]:
            for fid, meta in self.metadata.get(ftype, {}).items():
                if str(meta.get("gnis_id")) == str(gnis_id):
                    features.append(self.get_polygon_by_id(fid))
        return [f for f in features if f is not None]

    def search_by_watershed_code(self, fwa_watershed_code: str) -> List[FWAFeature]:
        """Search for all stream segments with a specific FWA watershed code."""
        features = []
        for linear_id, metadata in self.metadata.get(FeatureType.STREAM, {}).items():
            if metadata.get("fwa_watershed_code") == fwa_watershed_code:
                features.append(self.get_stream_by_id(linear_id))
        return features

    def search_by_blue_line_key(self, blue_line_key: str) -> List[FWAFeature]:
        """Search for all features (streams AND polygons) with a specific Blue Line Key."""
        features = []
        for lid, meta in self.metadata.get(FeatureType.STREAM, {}).items():
            if str(meta.get("blue_line_key")) == str(blue_line_key):
                features.append(self.get_stream_by_id(lid))
        for ftype in [FeatureType.LAKE, FeatureType.WETLAND, FeatureType.MANMADE]:
            for fid, meta in self.metadata.get(ftype, {}).items():
                if str(meta.get("blue_line_key")) == str(blue_line_key):
                    features.append(self.get_polygon_by_id(fid))
        return [f for f in features if f is not None]

    # --- New Helper Accessors ---

    def get_feature_by_id(self, feature_id: str) -> Optional[FWAFeature]:
        """
        Fetch a single unique feature by its record identifier.
        Supports linear_feature_id (streams) or waterbody_poly_id (polygons).
        """
        # 1. Try stream segment
        stream = self.get_stream_by_id(feature_id)
        if stream:
            return stream

        # 2. Try specific polygon record
        return self.get_polygon_by_id(feature_id)

    def get_feature_by_type_and_id(
        self, ftype: FeatureType, feature_id: str
    ) -> Optional[FWAFeature]:
        """Fetch a feature knowing its type and ID."""
        if ftype == FeatureType.STREAM:
            return self.get_stream_by_id(feature_id)
        return self.get_polygon_by_id(feature_id)

    def get_feature_type_from_id(self, feature_id: str) -> FeatureType:
        """Determine feature type from ID by checking existence in metadata collections."""
        if not feature_id:
            return FeatureType.UNKNOWN
        for ftype in [
            FeatureType.STREAM,
            FeatureType.LAKE,
            FeatureType.WETLAND,
            FeatureType.MANMADE,
        ]:
            if feature_id in self.metadata.get(ftype, {}):
                return ftype
        return FeatureType.UNKNOWN
