"""
FWA Metadata Gazetteer

Loads and queries the stream_metadata.pickle file generated by metadata_builder.py
to provide fast waterbody name lookups for regulation linking.

Also loads enriched KML points (unnamed lakes, future landmarks) for additional matching.
"""

import pickle
import json
from pathlib import Path
from typing import List, Dict, Optional
from dataclasses import dataclass
import logging


logger = logging.getLogger(__name__)


@dataclass
class FWAFeature:
    """
    Represents a feature from the FWA (Freshwater Atlas) database.

    This is a simplified representation for MVP. In production, this would
    come from the actual FWA geodatabase.
    """

    fwa_id: str
    name: str
    geometry_type: str  # "polygon", "multilinestring", "point"
    region: str
    gnis_name: Optional[str] = (
        None  # Official geographic names (GNIS_NAME or GNIS_NAME_1)
    )
    gnis_id: Optional[str] = (
        None  # GNIS_ID_1 for polygons (helps deduplicate same lake)
    )
    gnis_name_2: Optional[str] = None  # Alternate/historical name (GNIS_NAME_2)
    gnis_id_2: Optional[str] = None  # Alternate GNIS ID (GNIS_ID_2)
    fwa_watershed_code: Optional[str] = None  # FWA watershed code for streams
    mgmt_units: Optional[List[str]] = None  # Management units this feature appears in
    waterbody_key: Optional[str] = None  # Waterbody key for lakes/wetlands/manmade
    matched_via: Optional[str] = (
        None  # Track which name matched: 'gnis_name' or 'gnis_name_2'
    )

    def __eq__(self, other):
        if not isinstance(other, FWAFeature):
            return False
        return self.fwa_id == other.fwa_id

    def __hash__(self):
        return hash(self.fwa_id)


class MetadataGazetteer:
    """
    Gazetteer backed by stream_metadata.pickle file.

    The metadata file contains:
    - zone_metadata: Zone information
    - streams: Stream features with linear_feature_id, gnis_name, zones, etc.
    - lakes: Lake polygon features with waterbody_key, gnis_name, zones
    - wetlands: Wetland features
    - manmade: Manmade waterbody features

    Structure of stream metadata entry:
    {
        "linear_feature_id": "123456",
        "gnis_name": "Elk River",
        "fwa_watershed_code": "...",
        "waterbody_key": "123",
        "lake_name": "",
        "stream_tributary_of": "...",  # NOTE: DO NOT USE for tributary logic
        "zones": ["4"],
        "mgmt_units": ["4-15", "4-16"],
        "cross_boundary": False,
        ...
    }

    IMPORTANT: The stream_tributary_of and lake_tributary_of fields in the
    metadata are NOT suitable for our tributary enrichment logic. Use graph
    traversal from fwa_bc_primal_full.gpickle instead.

    Structure of lake/wetland/manmade metadata entry:
    {
        "waterbody_key": "456",
        "gnis_name": "Adams Lake",
        "feature_type": "lakes",
        "zones": ["3"],
        "mgmt_units": ["3-12"]
    }
    """

    def __init__(self, metadata_path: Path, enriched_kml_path: Path = None):
        """
        Initialize gazetteer from metadata pickle file and enriched KML points.

        Args:
            metadata_path: Path to stream_metadata.pickle file
            enriched_kml_path: Path to enriched_kml_points.json (optional)
        """
        self.metadata_path = metadata_path
        self.enriched_kml_path = enriched_kml_path
        self.metadata = None
        self.enriched_kml_data = None
        self.name_index: Dict[str, List[FWAFeature]] = {}

        self._load_metadata()
        if self.enriched_kml_path:
            self._load_enriched_kml()
        self._build_index()

    def _load_metadata(self):
        """Load metadata from pickle file."""
        logger.info(f"Loading FWA metadata from: {self.metadata_path}")

        with open(self.metadata_path, "rb") as f:
            self.metadata = pickle.load(f)

        # Log summary
        logger.info(f"  Zones: {len(self.metadata.get('zone_metadata', {}))}")
        logger.info(f"  Streams: {len(self.metadata.get('streams', {})):,}")
        logger.info(f"  Lakes: {len(self.metadata.get('lakes', {})):,}")
        logger.info(f"  Wetlands: {len(self.metadata.get('wetlands', {})):,}")
        logger.info(f"  Manmade: {len(self.metadata.get('manmade', {})):,}")

    def _load_enriched_kml(self):
        """Load enriched KML points from JSON file."""
        if not self.enriched_kml_path.exists():
            logger.warning(f"Enriched KML file not found: {self.enriched_kml_path}")
            return

        logger.info(f"Loading enriched KML points from: {self.enriched_kml_path}")

        with open(self.enriched_kml_path, "r", encoding="utf-8") as f:
            self.enriched_kml_data = json.load(f)

        points_count = len(self.enriched_kml_data.get("points", []))
        logger.info(f"  Loaded {points_count} enriched KML points")

    def _build_index(self):
        """Build name-based index from metadata."""
        logger.info("Building name index...")

        # Index streams by gnis_name
        for linear_id, stream_data in self.metadata.get("streams", {}).items():
            gnis_name = stream_data.get("gnis_name", "").strip()

            if gnis_name:
                # Create FWAFeature from stream metadata
                feature = FWAFeature(
                    fwa_id=linear_id,
                    name=gnis_name,
                    geometry_type="multilinestring",
                    region=self._zones_to_region(stream_data.get("zones", [])),
                    gnis_name=gnis_name,
                    fwa_watershed_code=stream_data.get("fwa_watershed_code"),
                    mgmt_units=stream_data.get("mgmt_units", []),
                )

                # Index by normalized name
                normalized = self._normalize_for_index(gnis_name)
                if normalized not in self.name_index:
                    self.name_index[normalized] = []
                self.name_index[normalized].append(feature)

        # Index lakes, wetlands, manmade by gnis_name and gnis_name_2
        for feature_type in ["lakes", "wetlands", "manmade"]:
            geometry_type = (
                "polygon"
                if feature_type in ["lakes", "wetlands", "manmade"]
                else "point"
            )

            for waterbody_key, feature_data in self.metadata.get(
                feature_type, {}
            ).items():
                gnis_name = feature_data.get("gnis_name", "").strip()
                gnis_name_2 = feature_data.get("gnis_name_2", "").strip()

                # Index GNIS_NAME (primary)
                if gnis_name:
                    feature = FWAFeature(
                        fwa_id=waterbody_key,
                        name=gnis_name,
                        geometry_type=geometry_type,
                        region=self._zones_to_region(feature_data.get("zones", [])),
                        gnis_name=gnis_name,
                        gnis_id=feature_data.get("gnis_id"),
                        gnis_name_2=gnis_name_2,
                        gnis_id_2=feature_data.get("gnis_id_2"),
                        fwa_watershed_code=feature_data.get("fwa_watershed_code"),
                        mgmt_units=feature_data.get("mgmt_units", []),
                        waterbody_key=waterbody_key,
                        matched_via="gnis_name",
                    )

                    normalized = self._normalize_for_index(gnis_name)
                    if normalized not in self.name_index:
                        self.name_index[normalized] = []
                    self.name_index[normalized].append(feature)

                # Index GNIS_NAME_2 (alternate) separately
                if gnis_name_2:
                    feature_2 = FWAFeature(
                        fwa_id=waterbody_key,
                        name=gnis_name_2,  # Use alternate name for display
                        geometry_type=geometry_type,
                        region=self._zones_to_region(feature_data.get("zones", [])),
                        gnis_name=gnis_name,  # Keep primary name for reference
                        gnis_id=feature_data.get("gnis_id"),
                        gnis_name_2=gnis_name_2,
                        gnis_id_2=feature_data.get("gnis_id_2"),
                        fwa_watershed_code=feature_data.get("fwa_watershed_code"),
                        mgmt_units=feature_data.get("mgmt_units", []),
                        waterbody_key=waterbody_key,
                        matched_via="gnis_name_2",  # Track that this matched via alternate name
                    )

                    normalized_2 = self._normalize_for_index(gnis_name_2)
                    if normalized_2 not in self.name_index:
                        self.name_index[normalized_2] = []
                    self.name_index[normalized_2].append(feature_2)

        # Index enriched KML points (unnamed lakes, future landmarks)
        if self.enriched_kml_data:
            for point_data in self.enriched_kml_data.get("points", []):
                name = point_data.get("name", "").strip()

                if name:
                    # Generate a unique ID for this KML point
                    kml_id = (
                        f"kml_{hash((point_data['longitude'], point_data['latitude']))}"
                    )

                    # Use whichever waterbody_key is available (lake, marsh, or manmade)
                    waterbody_key = (
                        point_data.get("lake_waterbody_key")
                        or point_data.get("marsh_waterbody_key")
                        or point_data.get("manmade_waterbody_key")
                    )

                    # Get fwa_watershed_code directly
                    fwa_watershed_code = point_data.get("fwa_watershed_code")

                    feature = FWAFeature(
                        fwa_id=kml_id,
                        name=name,
                        geometry_type="point",
                        region=point_data.get("region", "Unknown"),
                        gnis_name=name,
                        fwa_watershed_code=fwa_watershed_code,
                        mgmt_units=point_data.get("mgmt_units", []),
                        waterbody_key=waterbody_key,
                    )

                    normalized = self._normalize_for_index(name)
                    if normalized not in self.name_index:
                        self.name_index[normalized] = []
                    self.name_index[normalized].append(feature)

        logger.info(f"  Indexed {len(self.name_index):,} unique waterbody names")

    def _zones_to_region(self, zones: List[str]) -> str:
        """
        Convert zone list to region identifier.

        Args:
            zones: List of zone numbers (e.g., ["4"])

        Returns:
            Region identifier (e.g., "Region 4")
        """
        if not zones:
            return "Unknown"

        # Use first zone if multiple (cross-boundary)
        primary_zone = zones[0]
        return f"Region {primary_zone}"

    def _normalize_for_index(self, name: str) -> str:
        """Normalize name for indexing (title case, stripped)."""
        return name.strip().title()

    def search(self, name: str, region: Optional[str] = None) -> List[FWAFeature]:
        """
        Search for FWA features by name.

        Args:
            name: Waterbody name to search for
            region: Optional region filter (e.g., "Region 4")

        Returns:
            List of matching FWAFeature objects
        """
        normalized = self._normalize_for_index(name)
        matches = self.name_index.get(normalized, [])

        # Filter by region if provided
        if region:
            matches = [f for f in matches if f.region == region]

        return matches

    def get_stream_metadata(self, linear_feature_id: str) -> Optional[Dict]:
        """
        Get full metadata for a stream feature.

        Args:
            linear_feature_id: Stream's linear_feature_id

        Returns:
            Full metadata dict or None if not found
        """
        return self.metadata.get("streams", {}).get(linear_feature_id)

    def get_stream_by_id(self, linear_feature_id: str) -> Optional["FWAFeature"]:
        """
        Get stream feature as FWAFeature by linear_feature_id.

        Args:
            linear_feature_id: Stream's linear_feature_id

        Returns:
            FWAFeature or None if not found
        """
        metadata = self.get_stream_metadata(linear_feature_id)
        if not metadata:
            return None

        return FWAFeature(
            fwa_id=linear_feature_id,
            name=metadata.get("gnis_name") or linear_feature_id,
            geometry_type="multilinestring",
            gnis_id=metadata.get("gnis_id"),
            waterbody_key=None,
            fwa_watershed_code=metadata.get("fwa_watershed_code"),
            mgmt_units=metadata.get("zones", []),
            region=metadata.get("region"),
        )

    def get_polygon_metadata(
        self, waterbody_key: str, feature_type: str = None
    ) -> Optional[Dict]:
        """
        Get full metadata for a polygon feature (lake/wetland/manmade).

        Args:
            waterbody_key: Waterbody key
            feature_type: Optional filter ('lakes', 'wetlands', 'manmade')

        Returns:
            Full metadata dict or None if not found
        """
        if feature_type:
            return self.metadata.get(feature_type, {}).get(waterbody_key)

        # Search all polygon types
        for ftype in ["lakes", "wetlands", "manmade"]:
            result = self.metadata.get(ftype, {}).get(waterbody_key)
            if result:
                return result

        return None

    def get_zone_metadata(self, zone_number: str) -> Optional[Dict]:
        """
        Get metadata for a specific zone.

        Args:
            zone_number: Zone number (e.g., "4")

        Returns:
            Zone metadata dict or None if not found
        """
        return self.metadata.get("zone_metadata", {}).get(zone_number)

    def get_features_in_zone(
        self, zone_number: str, feature_type: str = "streams"
    ) -> List[Dict]:
        """
        Get all features in a specific zone.

        Args:
            zone_number: Zone number (e.g., "4")
            feature_type: 'streams', 'lakes', 'wetlands', or 'manmade'

        Returns:
            List of feature metadata dicts
        """
        features = []

        for feature_id, metadata in self.metadata.get(feature_type, {}).items():
            if zone_number in metadata.get("zones", []):
                features.append(metadata)

        return features

    def get_waterbody_by_key(self, waterbody_key: str) -> Optional[FWAFeature]:
        """
        Get FWA feature by exact waterbody_key.

        Used for DirectMatch lookups.

        Args:
            waterbody_key: Waterbody key (used for lakes, wetlands, manmade)

        Returns:
            FWAFeature if found, None otherwise
        """
        # Check lakes, wetlands, manmade
        # Try both string and int versions since keys might be stored as either
        for feature_type in ["lakes", "wetlands", "manmade"]:
            # Try string key first
            feature_data = self.metadata.get(feature_type, {}).get(waterbody_key)
            # If not found, try converting to int
            if not feature_data:
                try:
                    int_key = int(waterbody_key)
                    feature_data = self.metadata.get(feature_type, {}).get(int_key)
                except (ValueError, TypeError):
                    pass

            if feature_data:
                gnis_name = feature_data.get("gnis_name", "").strip()

                geometry_type = "polygon"

                return FWAFeature(
                    fwa_id=waterbody_key,
                    name=gnis_name or waterbody_key,
                    geometry_type=geometry_type,
                    region=self._zones_to_region(feature_data.get("zones", [])),
                    gnis_name=gnis_name,
                    gnis_id=feature_data.get("gnis_id"),
                    fwa_watershed_code=feature_data.get("fwa_watershed_code"),
                    mgmt_units=feature_data.get("mgmt_units", []),
                    waterbody_key=waterbody_key,
                )

        return None

    def get_feature_by_id(self, feature_id: str) -> Optional[FWAFeature]:
        """
        Get FWA feature by ID (linear_feature_id for streams, waterbody_key for polygons).

        Used for DirectMatch lookups.

        Args:
            feature_id: Linear feature ID or waterbody key

        Returns:
            FWAFeature if found, None otherwise
        """
        # Try as stream linear_feature_id first
        stream_data = self.metadata.get("streams", {}).get(feature_id)
        if stream_data:
            gnis_name = stream_data.get("gnis_name", "").strip()

            return FWAFeature(
                fwa_id=feature_id,
                name=gnis_name or feature_id,
                geometry_type="multilinestring",
                region=self._zones_to_region(stream_data.get("zones", [])),
                gnis_name=gnis_name,
                fwa_watershed_code=stream_data.get("fwa_watershed_code"),
                mgmt_units=stream_data.get("mgmt_units", []),
            )

        # Try as waterbody_key (lakes, wetlands, manmade)
        return self.get_waterbody_by_key(feature_id)

    def search_by_gnis_id(self, gnis_id: str) -> List[FWAFeature]:
        """
        Search for all features with a specific GNIS ID.

        Used for DirectMatch lookups - returns ALL polygons of a lake with this GNIS ID.

        Args:
            gnis_id: GNIS identifier

        Returns:
            List of FWAFeature objects with matching GNIS ID
        """
        features = []

        # Search in lakes, wetlands, manmade
        for feature_type in ["lakes", "wetlands", "manmade"]:
            for waterbody_key, metadata in self.metadata.get(feature_type, {}).items():
                if str(metadata.get("gnis_id")) == str(gnis_id):
                    gnis_name = metadata.get("gnis_name", "").strip()

                    features.append(
                        FWAFeature(
                            fwa_id=waterbody_key,
                            name=gnis_name or waterbody_key,
                            geometry_type="polygon",
                            region=self._zones_to_region(metadata.get("zones", [])),
                            gnis_name=gnis_name,
                            gnis_id=metadata.get("gnis_id"),
                            mgmt_units=metadata.get("mgmt_units", []),
                            waterbody_key=waterbody_key,
                        )
                    )

        return features

    def search_by_watershed_code(self, fwa_watershed_code: str) -> List[FWAFeature]:
        """
        Search for all stream segments with a specific FWA watershed code.

        Used for DirectMatch lookups - returns ALL segments of a stream.

        Args:
            fwa_watershed_code: FWA watershed code

        Returns:
            List of FWAFeature objects (stream segments) with matching watershed code
        """
        features = []

        for linear_feature_id, metadata in self.metadata.get("streams", {}).items():
            if metadata.get("fwa_watershed_code") == fwa_watershed_code:
                gnis_name = metadata.get("gnis_name", "").strip()

                features.append(
                    FWAFeature(
                        fwa_id=linear_feature_id,
                        name=gnis_name or linear_feature_id,
                        geometry_type="multilinestring",
                        region=self._zones_to_region(metadata.get("zones", [])),
                        gnis_name=gnis_name,
                        fwa_watershed_code=metadata.get("fwa_watershed_code"),
                        mgmt_units=metadata.get("mgmt_units", []),
                    )
                )

        return features
