"""The outside-BC mask, as one small GeoJSON file.

    python -m pipeline.deliver.tiles.boundary

WHY NOT A TILE LAYER. It was one, twice. The first version cut the province out of the
WHOLE WORLD, so the shape landed in every tile of the entire pyramid — about 1 GB for one
flat wash. Bounded to the province's neighbourhood it measures 0.8 MB tiled, which is fine
but still buys nothing: the mask is a single polygon of 2,308 vertices that never changes
between builds, and putting it in the archive means a fifteen-minute tile rebuild every
time somebody wants to try a different opacity.

As a file it is ~50 KB, MapLibre reads it as a `geojson` source with no extra machinery,
and it is one static asset served beside the tiles.

WHY IT EXISTS AT ALL. The tiles cover a bounding box whose corners are Alberta, Alaska,
Washington and the Pacific. A river that crosses the border keeps being drawn on the far
side with no regulation attached — which reads as "nothing restricts you here" when it
means "this is not our jurisdiction". Those are opposite sentences.
"""

from __future__ import annotations

import json
from pathlib import Path
from pipeline.common.curated import CURATED, SOURCE
from pipeline.common.curated import REPO_ROOT

# ~200 m. This is a visual wash, not a legal boundary: the fjords do not need to be right,
# and 2,308 vertices of coastline cost more than the effect is worth.
SIMPLIFY_DEG = 0.002
# Degrees of margin around the province. The mask has to cover every pixel a reader can
# pan to; one that stops short leaves a band of undimmed foreign ground along the edge.
MARGIN_DEG = 6.0


def build(boundary: Path, out: Path) -> Path:
    import geopandas as gpd
    from shapely.geometry import box, mapping

    bc = gpd.read_file(boundary).to_crs(4326).geometry.union_all().simplify(SIMPLIFY_DEG)
    minx, miny, maxx, maxy = bc.bounds
    frame = box(minx - MARGIN_DEG, miny - MARGIN_DEG, maxx + MARGIN_DEG, maxy + MARGIN_DEG)

    # The cookie cutter: a rectangle with the province punched out of it. One polygon with
    # an interior ring, which is exactly what a fill needs to paint "everywhere but here".
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps({
        "type": "FeatureCollection",
        "$comment": f"GENERATED by python -m pipeline.deliver.tiles.boundary from {boundary.name}. "
                    f"The frame minus British Columbia, simplified to {SIMPLIFY_DEG} deg.",
        "features": [{"type": "Feature", "properties": {"side": "outside"},
                      "geometry": mapping(frame.difference(bc))}],
    }, separators=(",", ":")))
    print(f"  ✅ {out}  {out.stat().st_size / 1024:.0f} KB")
    return out


if __name__ == "__main__":
    root = REPO_ROOT
    build(SOURCE / "bc_boundary.geojson", SOURCE / "bc_outside.geojson")
