"""The outside-BC mask, as one small GeoJSON file.

    python -m pipeline.deliver.tiles.boundary

WHY NOT A TILE LAYER. It was one, twice. The first version cut the province out of the
WHOLE WORLD, so the shape landed in every tile of the entire pyramid — about 1 GB for one
flat wash. Bounded to the province's neighbourhood it measures 0.8 MB tiled, which is fine
but still buys nothing: the mask is a single polygon of 2,308 vertices that never changes
between builds, and putting it in the archive means a fifteen-minute tile rebuild every
time somebody wants to try a different opacity.

As a file it is ~50 KB, MapLibre reads it as a `geojson` source with no extra machinery,
and it is one static asset served beside the tiles.

WHY IT EXISTS AT ALL. The tiles cover a bounding box whose corners are Alberta, Alaska,
Washington and the Pacific. A river that crosses the border keeps being drawn on the far
side with no regulation attached — which reads as "nothing restricts you here" when it
means "this is not our jurisdiction". Those are opposite sentences.
"""

from __future__ import annotations

import json
from pathlib import Path
from pipeline.common.curated import CURATED, SOURCE
from pipeline.common.curated import REPO_ROOT

# ~200 m. This is a visual wash, not a legal boundary: the fjords do not need to be right,
# and 2,308 vertices of coastline cost more than the effect is worth.
SIMPLIFY_DEG = 0.002
# Degrees of margin around the province. The mask has to cover every pixel a reader can
# pan to; one that stops short leaves a band of undimmed foreign ground along the edge.
#
# THIS WAS 6.0 AND IT WAS NOT ENOUGH. At the app's minimum zoom (4) a phone viewport spans
# roughly 19 deg of longitude and 24 deg of latitude, and BC itself is 25 x 12 — so the
# frame (42.2N-66.0N) ended inside the visible area and a band of bright, undimmed
# Washington sat along the bottom of the screen. Exactly the failure the paragraph above
# describes, discovered by zooming out.
#
# 30 deg costs FOUR VERTICES — the file's size is the province's 1,552-point coastline, not
# the frame — and comfortably exceeds the widest viewport the app's `maxBounds` can produce
# at `MIN_ZOOM`. The app's camera limits and this number are related, so if either moves,
# check the other: `packages/core/src/ladder.ts` holds the camera side.
MARGIN_DEG = 30.0

# Web Mercator cannot represent the poles, and BC is far enough north that 60 + 30 would
# ask for 90. Clamped rather than reduced, so the southern margin keeps its full reach.
LAT_LIMIT = 85.0


def build(boundary: Path, out: Path) -> Path:
    import geopandas as gpd
    from shapely.geometry import box, mapping

    bc = gpd.read_file(boundary).to_crs(4326).geometry.union_all().simplify(SIMPLIFY_DEG)
    minx, miny, maxx, maxy = bc.bounds
    frame = box(max(minx - MARGIN_DEG, -180.0), max(miny - MARGIN_DEG, -LAT_LIMIT),
                min(maxx + MARGIN_DEG, 180.0), min(maxy + MARGIN_DEG, LAT_LIMIT))

    # The cookie cutter: a rectangle with the province punched out of it. One polygon with
    # an interior ring, which is exactly what a fill needs to paint "everywhere but here".
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps({
        "type": "FeatureCollection",
        "$comment": f"GENERATED by python -m pipeline.deliver.tiles.boundary from {boundary.name}. "
                    f"The frame minus British Columbia, simplified to {SIMPLIFY_DEG} deg.",
        "features": [{"type": "Feature", "properties": {"side": "outside"},
                      "geometry": mapping(frame.difference(bc))}],
    }, separators=(",", ":")))
    print(f"  ✅ {out}  {out.stat().st_size / 1024:.0f} KB")
    return out


if __name__ == "__main__":
    root = REPO_ROOT
    build(SOURCE / "bc_boundary.geojson", SOURCE / "bc_outside.geojson")
