// GENERATED by `python -m pipeline.tools.emit_calendar`. Do not edit.
//
// THE CALENDAR SPEC (pipeline/common/calendar_spec.py): the regulations' calendar, one source
// for Python, TypeScript and the reference page. Day 1..366 on the LEAP calendar: Jan 1 = 1,
// Feb 29 = 60, Mar 1 = 61 in EVERY year, Dec 31 = 366, so a printed "Mar 1" is the
// same day whether or not the year has a Feb 29. Logic that reads these (a `Date` in local
// time) stays in the module that runs it.

/** A day of the week, as the catalogue's `when.weekdays` names it. */
export type Weekday = "Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday" | "Saturday" | "Sunday";

/** The days of the leap calendar. */
export const CALENDAR_DAYS = 366;

/** Feb 29's day on the leap calendar. */
export const LEAP_DAY = 60;

/** The months as the book abbreviates them, January first. */
export const MONTHS: readonly string[] = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

/** The last day of each month on the leap calendar (February has 29). */
export const MONTH_LAST_DAY: readonly number[] = [31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];

/** The days before each month on the leap calendar (January: 0). */
export const DAYS_BEFORE_MONTH: readonly number[] = [0, 31, 60, 91, 121, 152, 182, 213, 244, 274, 305, 335];

/** The last day of each month in a common year (no Feb 29) — the book's printed year. */
export const COMMON_YEAR_MONTH_LAST_DAY: readonly number[] = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];

/** The days of the week, Monday first (a weekday bitmask's bit 0). */
export const WEEKDAYS: readonly Weekday[] = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];
