// GENERATED by `python -m pipeline.tools.emit_gauge_policy`. Do not edit.
//
// The source of truth is `TRUST_BANDS` in pipeline/hydro/shed.py, which is also where the
// algorithm lives. The app never computes a band: it reads the one the bundler wrote into
// `section_gauge.trust`. These constants exist so the two sides agree on the VOCABULARY --
// what the words are and where the floors sit -- not so the rule can be run twice.

/** The bands the pipeline can write. A reach below the last floor gets NO ROW at all,
 *  which is why there is no "none" here: absence is the fourth outcome. */
export type GaugeTrust = "good" | "fair" | "weak";

/** Fraction of the gauge's own drainage that a reach accounts for, at each band's floor. */
export const TRUST_FLOOR = {
  good: 0.1,
  fair: 0.01,
  weak: 0.001,
} as const;

/** The same thing in order, worst floor last -- for rendering a scale or a legend. */
export const TRUST_BANDS: readonly (readonly [GaugeTrust, number])[] = [
  ["good", 0.1],
  ["fair", 0.01],
  ["weak", 0.001],
];
