"""Emit THE CALENDAR SPEC as TypeScript, JSON and the reference page's JS, so no copy is hand-typed.

    python -m pipeline.tools.emit_calendar          # write them
    python -m pipeline.tools.emit_calendar --check  # fail if one is stale or hand-edited (CI)

WHY THIS EXISTS. The regulations' calendar (day 1..366 on the leap calendar, Feb 29 = 60, the
month tables, the weekday names) was spelled four times: the catalogue's `dates` part, the
delivery's `calendar.py`, `@app/core` `statusIndex.ts` (`BEFORE`) and the reference page's script
(`LEAP0`, `DIM`, `MON`, `WEEK`). They agreed, and nothing made them. The source is now
`pipeline/common/calendar_spec.py`; both Python owners read it, and this writes the other
languages' copies from it (AGENTS 40, the `emit_gauge_policy` / `answers.model` pattern).

WHAT IS SHARED AND WHAT IS NOT. The constants are generated. The logic that reads them is the
platform's: `dayOfYear` reads a JS `Date` in local time (statusIndex.ts), the page walks the
book's 365-day year — neither is the Python's to run, and both read the generated constants.
`test_dataflow_gates.py` gate 4 refuses a calendar table spelled by hand anywhere else.
"""
from __future__ import annotations

import argparse
import json
import sys

from pipeline.common import calendar_spec as SPEC
from pipeline.common.curated import REPO_ROOT

ROOT = REPO_ROOT
CORE = ROOT / "app" / "packages" / "core" / "src"
OUT_TS = CORE / "calendar.generated.ts"
#: The same spec as JSON, for node tools that cannot import a workspace TypeScript package.
OUT_JSON = CORE / "calendar.generated.json"
#: The reference page's copy: `page_data.write_html` inlines it ahead of `page_v36.js`.
OUT_PAGE_JS = ROOT / "pipeline" / "deliver" / "answers" / "reference" / "calendar.generated.js"

_BY = "python -m pipeline.tools.emit_calendar"
_SRC = "pipeline/common/calendar_spec.py"


def _list(xs) -> str:
    return "[" + ", ".join(json.dumps(x) for x in xs) + "]"


def render_ts() -> str:
    """The TypeScript, byte for byte."""
    weekday = " | ".join(json.dumps(w) for w in SPEC.WEEKDAYS)
    return f'''// GENERATED by `{_BY}`. Do not edit.
//
// THE CALENDAR SPEC ({_SRC}): the regulations' calendar, one source
// for Python, TypeScript and the reference page. Day 1..{SPEC.DAYS} on the LEAP calendar: Jan 1 = 1,
// Feb 29 = {SPEC.LEAP_DAY}, Mar 1 = {SPEC.LEAP_DAY + 1} in EVERY year, Dec 31 = {SPEC.DAYS}, so a printed "Mar 1" is the
// same day whether or not the year has a Feb 29. Logic that reads these (a `Date` in local
// time) stays in the module that runs it.

/** A day of the week, as the catalogue's `when.weekdays` names it. */
export type Weekday = {weekday};

/** The days of the leap calendar. */
export const CALENDAR_DAYS = {SPEC.DAYS};

/** Feb 29's day on the leap calendar. */
export const LEAP_DAY = {SPEC.LEAP_DAY};

/** The months as the book abbreviates them, January first. */
export const MONTHS: readonly string[] = {_list(SPEC.MONTHS)};

/** The last day of each month on the leap calendar (February has 29). */
export const MONTH_LAST_DAY: readonly number[] = {_list(SPEC.LAST_DAY)};

/** The days before each month on the leap calendar (January: 0). */
export const DAYS_BEFORE_MONTH: readonly number[] = {_list(SPEC.DAYS_BEFORE)};

/** The last day of each month in a common year (no Feb 29) — the book's printed year. */
export const COMMON_YEAR_MONTH_LAST_DAY: readonly number[] = {_list(SPEC.COMMON_YEAR_LAST_DAY)};

/** The days of the week, Monday first (a weekday bitmask's bit 0). */
export const WEEKDAYS: readonly Weekday[] = {_list(SPEC.WEEKDAYS)};
'''


def render_json() -> str:
    return json.dumps({"_generated_by": _BY, "_source": _SRC, **SPEC.as_json()}, indent=2) + "\n"


def render_page_js() -> str:
    """The reference page's copy: one frozen `CALENDAR` the page script reads its tables from."""
    return (f"// GENERATED by `{_BY}`. Do not edit.\n"
            f"// THE CALENDAR SPEC ({_SRC}); `page_data.write_html` inlines it\n"
            "// ahead of page_v36.js, which reads its tables from CALENDAR.\n"
            f"const CALENDAR = Object.freeze({json.dumps(SPEC.as_json(), separators=(',', ':'))});\n")


def outputs():
    return ((OUT_TS, render_ts()), (OUT_JSON, render_json()), (OUT_PAGE_JS, render_page_js()))


def stale(outs=None) -> list:
    """The generated files that are missing or differ from what the spec renders."""
    return [(p, want) for p, want in (outs if outs is not None else outputs())
            if not p.exists() or p.read_text(encoding="utf-8") != want]


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if a committed file differs (for CI)")
    a = ap.parse_args(argv)
    bad = stale()
    if not bad:
        print("calendar up to date: " + ", ".join(p.name for p, _ in outputs()))
        return 0
    if a.check:
        for p, _ in bad:
            print(f"STALE: {p.relative_to(ROOT)} does not match {_SRC}", file=sys.stderr)
        print(f"  run: {_BY}", file=sys.stderr)
        return 1
    for p, want in bad:
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(want, encoding="utf-8")
        print(f"wrote {p.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
