/**
 * Regulations Service
 * 
 * Loads and caches regulation data from the static JSON file.
 * The regulations.json file is generated by the Python pipeline and
 * served as a static asset from Cloudflare Pages.
 */

export interface Regulation {
  waterbody_name: string;
  waterbody_key: string | null;
  region: string | null;
  management_units: string[];
  
  // Rule details
  rule_text: string;
  restriction_type: string;
  restriction_details: string;
  dates: string[] | string | null;  // Can be array, string "null", or actual null
  
  // Scope
  scope_type: string;
  scope_location: string | null;
  includes_tributaries: boolean | null;
}

type RegulationsLookup = Record<string, Regulation>;

class RegulationsService {
  private regulations: RegulationsLookup | null = null;
  private loadPromise: Promise<RegulationsLookup> | null = null;

  /**
   * Load regulations from static JSON file.
   * Automatically caches the result for subsequent calls.
   */
  async loadRegulations(): Promise<RegulationsLookup> {
    // Return cached data if available
    if (this.regulations) {
      return this.regulations;
    }

    // Return existing promise if already loading
    if (this.loadPromise) {
      return this.loadPromise;
    }

    // Start loading
    this.loadPromise = fetch('/data/regulations.json')
      .then(response => {
        if (!response.ok) {
          throw new Error(`Failed to load regulations: ${response.statusText}`);
        }
        return response.json();
      })
      .then(data => {
        this.regulations = data;
        this.loadPromise = null;
        console.log(`Loaded ${Object.keys(data).length} regulations`);
        return data;
      })
      .catch(error => {
        this.loadPromise = null;
        console.error('Failed to load regulations:', error);
        throw error;
      });

    return this.loadPromise;
  }

  /**
   * Get regulations by IDs from feature properties.
   * 
   * @param regulationIds - Comma-separated string or array of regulation IDs
   * @returns Array of regulation objects
   */
  async getRegulations(regulationIds: string | string[]): Promise<Regulation[]> {
    const regulations = await this.loadRegulations();
    
    // Parse IDs
    const ids = typeof regulationIds === 'string' 
      ? regulationIds.split(',').map(id => id.trim())
      : regulationIds;

    // Lookup each ID
    return ids
      .map(id => regulations[id])
      .filter(Boolean); // Remove any missing regulations
  }

  /**
   * Get a single regulation by ID.
   */
  async getRegulation(regulationId: string): Promise<Regulation | null> {
    const regulations = await this.loadRegulations();
    return regulations[regulationId] || null;
  }

  /**
   * Preload regulations on app startup for faster first interaction.
   */
  preload(): void {
    this.loadRegulations().catch(console.error);
  }
}

// Export singleton instance
export const regulationsService = new RegulationsService();
