"""
Two-layer regulation table for regulation_mapping_v2.

Architecture
------------
Every synopsis row maps to exactly one entry.  There are two layers:

    BaseEntry    — auto-generated by running the v2 linker on
                   synopsis_raw_data.json.  Populated once, cached to JSON.

    OverrideEntry — manually authored corrections.  An OverrideEntry for a
                    given (region, name_verbatim) always wins over a BaseEntry.
                    These replace the current linking_corrections.py tables.

Both layers use MatchCriteria as their identity key:
    (name_verbatim, region, mus)

The 'mus' field on MatchCriteria is stored for audit / documentation purposes.
Lookup uses only (region, name_verbatim) as the index key — MU matching is
enforced during the initial natural-search phase, not at lookup time.  This
mirrors how the v1 correction tables work (region + name only).

Name variants
-------------
One entry can cover multiple synopsis names via name_variants.  Each variant
shares the same region as the primary criteria.  Both the primary name and all
variants are indexed so lookup always returns the same entry regardless of
which name appears in the synopsis row.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Union

from .reg_models import MatchCriteria


# ---------------------------------------------------------------------------
# Entry types
# ---------------------------------------------------------------------------


@dataclass
class BaseEntry:
    """Auto-generated from natural gazetteer search.

    Produced by running BaseEntryBuilder.build_table() on synopsis_raw_data.json.
    Empty fwa_refs means the natural search found nothing — the entry still
    exists so the absence is visible rather than silently omitted.

    link_method is an audit string ("natural_search", "not_found", etc.).
    name_variants are alternate synopsis names that resolve to this same
    waterbody (e.g. an Indigenous name alongside the GNIS name).
    """

    criteria: MatchCriteria
    fwa_refs: List[Dict[str, Any]] = field(default_factory=list)
    name_variants: List[str] = field(default_factory=list)
    link_method: str = "natural_search"

    def to_dict(self) -> Dict[str, Any]:
        return {
            "type": "base",
            "criteria": {
                "name_verbatim": self.criteria.name_verbatim,
                "region": self.criteria.region,
                "mus": self.criteria.mus,
            },
            "fwa_refs": self.fwa_refs,
            "name_variants": self.name_variants,
            "link_method": self.link_method,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "BaseEntry":
        c = data["criteria"]
        return cls(
            criteria=MatchCriteria(
                name_verbatim=c["name_verbatim"],
                region=c.get("region"),
                mus=c.get("mus", []),
            ),
            fwa_refs=data.get("fwa_refs", []),
            name_variants=data.get("name_variants", []),
            link_method=data.get("link_method", "natural_search"),
        )


@dataclass
class OverrideEntry:
    """Manually authored correction — always wins over a BaseEntry.

    Equivalent to the current DIRECT_MATCHES / SKIP_ENTRIES tables in
    linking_corrections.py, but every entry now carries a fully-qualified
    MatchCriteria (name + region + mus) so it can only match the precise
    synopsis row it was written for.

    skip = True  →  regulation intentionally skipped (not found / cross-listing).
    additional_info  →  injected as a 'Note' rule on the front end (permit info etc).
    """

    criteria: MatchCriteria
    note: str = ""
    fwa_refs: List[Dict[str, Any]] = field(default_factory=list)
    # Alternate synopsis names that also map to this entry.
    name_variants: List[str] = field(default_factory=list)
    skip: bool = False
    skip_reason: Optional[str] = None
    additional_info: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "type": "override",
            "criteria": {
                "name_verbatim": self.criteria.name_verbatim,
                "region": self.criteria.region,
                "mus": self.criteria.mus,
            },
            "note": self.note,
            "fwa_refs": self.fwa_refs,
            "name_variants": self.name_variants,
            "skip": self.skip,
            "skip_reason": self.skip_reason,
            "additional_info": self.additional_info,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "OverrideEntry":
        c = data["criteria"]
        return cls(
            criteria=MatchCriteria(
                name_verbatim=c["name_verbatim"],
                region=c.get("region"),
                mus=c.get("mus", []),
            ),
            note=data.get("note", ""),
            fwa_refs=data.get("fwa_refs", []),
            name_variants=data.get("name_variants", []),
            skip=data.get("skip", False),
            skip_reason=data.get("skip_reason"),
            additional_info=data.get("additional_info"),
        )


# ---------------------------------------------------------------------------
# Lookup engine
# ---------------------------------------------------------------------------

AnyEntry = Union[BaseEntry, OverrideEntry]


class MatchTable:
    """Merge base entries and overrides into one lookup index.

    Index key is (region, name_verbatim, frozenset(mus)).
    Override always wins over a base entry for the same key.
    Both primary names and name_variants are indexed.

    Lookup is fully qualified — all three fields must match exactly.
    When a synopsis row changes its MUs, the match breaks visibly instead of
    silently returning the stale entry.  That is the whole point.

    Usage
    -----
        table = MatchTable(bases, overrides)
        entry = table.lookup("ELK RIVER", "Region 3", ["3-5", "3-6"])
        # entry is OverrideEntry if one exists, otherwise BaseEntry, or None.
    """

    def __init__(
        self,
        bases: List[BaseEntry],
        overrides: List[OverrideEntry],
    ) -> None:
        # Index overrides first — they have priority.
        self._idx: Dict[tuple, AnyEntry] = {}

        for entry in overrides:
            self._index(entry)

        # Base entries fill gaps left by overrides.
        for entry in bases:
            key = self._make_key(
                entry.criteria.region,
                entry.criteria.name_verbatim,
                entry.criteria.mus,
            )
            if key not in self._idx:
                self._index(entry)

    @staticmethod
    def _make_key(
        region: Optional[str],
        name_verbatim: str,
        mus: List[str],
    ) -> tuple:
        """Stable, hashable index key including all three match dimensions."""
        return (region, name_verbatim, frozenset(mus))

    def _index(self, entry: AnyEntry) -> None:
        """Add an entry (and all its name variants) to the index."""
        key = self._make_key(
            entry.criteria.region,
            entry.criteria.name_verbatim,
            entry.criteria.mus,
        )
        self._idx[key] = entry
        for variant in entry.name_variants:
            vkey = self._make_key(entry.criteria.region, variant, entry.criteria.mus)
            # Don't overwrite an existing override with a variant reference.
            if vkey not in self._idx:
                self._idx[vkey] = entry

    def lookup(
        self,
        name_verbatim: str,
        region: Optional[str],
        mus: Optional[List[str]] = None,
    ) -> Optional[AnyEntry]:
        """Return the entry for (region, name_verbatim, mus), or None.

        mus must match exactly (same set of MU codes as stored in the entry).
        If you pass mus=None the key is built with an empty MU set, which only
        matches entries that were also stored with no MUs.
        """
        return self._idx.get(self._make_key(region, name_verbatim, mus or []))
