"""The frozen gauge match: the record, and reading and writing it.

WHY THIS IS NOT IN `generate/`. The build and the bundler READ this file; only the matcher
writes it. If the reader lived beside the matcher, every consumer would import the module
that needs 2.8 GB of pickled geometry and an STRtree over two million sections just to
learn where a station is — and "the build must not re-run matching" would be a convention
rather than a fact about the import graph.

So: the record and its IO live here, `generate/match.py` produces it, and
`consume/` reads it and cannot reach the matcher at all.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, fields
from pathlib import Path

from pipeline.curated import CURATED

@dataclass(frozen=True)
class StationMatch:
    """One station's outcome, addressed by keys the FWA owns rather than by a node id.

    NODE IDS ARE BUILD OUTPUT. `{blk}:{down_m}` is assigned by the sectionizer, so it moves
    the moment a river is cut differently — which the gauge splits do, deliberately, on the
    very next build. A match frozen as node ids is therefore stale by construction: it names
    sections the graph it is being read against does not have.

    THE ADDRESS IS A PLACE AND A WATER, and nothing derived.

        streams   the station's published coordinate + `wsc`, the FWA watershed code
        lakes     the station's published coordinate + `wbk`, the FWA waterbody key

    A route measure would work too — FWA measures survive re-sectioning — but it is a number
    WE compute from the coordinate, and freezing a derived value means every consumer
    inherits whatever we believed about projection on the day the file was written. The
    coordinate is the primary fact: ECCC publishes it, it does not move, and each consumer
    projects it itself against the graph in front of it.

        the build   a `gauge` point anchor at the coordinate, scoped by `wsc`
        the bundle  the nearest section on that water, taking the UPSTREAM one where the
                    gauge sits on a boundary — that is the water it has just measured

    One frozen fact, no cached derivative that can disagree with it.
    """
    station: str
    status: str                  # matched | no_match | unresolved
    resolved_by: str | None      # name+radius | alias | override
    distance_m: float | None
    reason: str | None = None
    # --- the address (empty when unmatched) ---
    lon: float | None = None     # the station's own published position
    lat: float | None = None
    wsc: str = ""                # FWA watershed code: the river and its side channels
    wbk: str = ""                # FWA waterbody key, when the station is on a lake
    # --- review aids, never an input to anything ---
    name: str = ""               # the water the atlas calls this, at the time of matching
    blk: str = ""                # the blue line it matched. Diagnostic; see the note above.
    node_id: str | None = None   # the node it matched IN THAT BUILD. Diagnostic only.
    #: Additional FWA keys a curated `bind` named, beyond the one in `wsc`/`wbk`. A lake
    #: outlet describes both the lake and the stream leaving it. RECORDED, NOT YET CONSUMED
    #: — widening the match to several waters reaches split_defs, nodes_for and the shed
    #: walk, so the curation is captured now and acted on when those are ready.
    also: tuple[str, ...] = ()


#: THE ONE FROZEN FACT about where BC's gauges are, committed and reviewable.
#:
#: Beside `splits.json` and `added_streams.build.json`, and generated the same way: run it
#: against a completed build, commit the answer, and the NEXT build reads it. It has to be
#: two-pass because matching compares a station's name against every name a node carries,
#: and those include `name_variants.json`, which is applied during the build.
MATCH_FILE = CURATED.gauges.matches


def write_match(matches: list[StationMatch], path: Path | None = None) -> Path:
    """Freeze the match. Sorted by station, so a diff reads as a list of gauges."""
    path = path or MATCH_FILE
    path.write_text(json.dumps({
        "_about": "Where each hydrometric station sits: its own published coordinate plus "
                  "the FWA key for the water it is on — `wsc` for a stream, `wbk` for a "
                  "lake. NOT node ids, which are build output and move whenever a river is "
                  "re-sectioned, and NOT a route measure, which is a number we derive from "
                  "the coordinate rather than a fact anyone published. GENERATED by "
                  "`python -m pipeline.gauges.generate.match --build <a completed build>`; do not "
                  "hand-edit. Read by pipeline.build (to cut rivers at their gauges) and by "
                  "pipeline.bundle (to place each station on a section).",
        "stations": [asdict(m) for m in sorted(matches, key=lambda m: m.station)],
    }, indent=1) + "\n", encoding="utf-8")
    return path


def read_match(path: Path | None = None) -> list[StationMatch]:
    """The frozen match, or an empty list if it has never been generated.

    TWO SHAPES, one meaning. A promoted file keys rows by station and carries `trust` and
    `evidence` alongside; the pre-promotion file was a bare list. Both parse to the same
    `StationMatch`, because everything downstream wants the ADDRESS — a coordinate and an
    FWA key — and does not care how confident anyone was about it.

    `wsc`/`wbk` arrive as lists in the promoted shape (a lake outlet legitimately describes
    both the lake and the stream below it). The first is the match; the rest go to `also`,
    which nothing consumes yet.
    """
    path = path or MATCH_FILE
    if not path.exists():
        return []
    blob = json.loads(path.read_text(encoding="utf-8")).get("stations", [])
    rows = list(blob.values()) if isinstance(blob, dict) else blob
    known = {f.name for f in fields(StationMatch)}
    out = []
    for r in rows:
        r = dict(r)
        extra = []
        for key in ("wsc", "wbk"):
            v = r.get(key)
            if isinstance(v, list):
                r[key] = v[0] if v else ""
                extra += v[1:]
        r["also"] = tuple(r.get("also") or ()) + tuple(extra)
        # A promoted row records a decision as `trust`; the reader keeps the status
        # vocabulary the rest of the pipeline speaks.
        trust = r.get("trust")
        if trust:
            r["status"] = {"wrong": "unresolved", "none": "no_match",
                           "candidate": "unresolved"}.get(trust, "matched")
        out.append(StationMatch(**{k: v for k, v in r.items() if k in known}))
    return out
