"""
FWA Metadata Gazetteer

Loads and queries the stream_metadata.pickle file generated by metadata_builder.py
to provide fast waterbody name lookups for regulation linking.

Also loads enriched KML points (unnamed lakes, future landmarks) for additional matching.
Supports admin boundary layers (parks, WMAs, watersheds) via pickle metadata + GPKG geometry.
"""

import pickle
import json
from pathlib import Path
from typing import List, Dict, Optional, Any, Set, Tuple
from dataclasses import dataclass
from enum import Enum
import logging

from fwa_pipeline.metadata_builder import (
    FeatureType,
    ADMIN_LAYER_CONFIG,
    ADMIN_FEATURE_TYPES,
)
from data.data_extractor import FWADataAccessor

logger = logging.getLogger(__name__)


@dataclass
class FWAFeature:
    """
    Represents a feature from the FWA database or an administrative boundary.

    Used uniformly for hydrological features (streams, lakes, wetlands,
    manmade) and admin boundary features (parks, WMAs, watersheds, etc.).
    """

    fwa_id: str
    geometry_type: str  # "polygon", "multilinestring", "point"
    # --- Zone / Region fields ---
    # ``zones`` and ``region_names`` are positionally paired: index *i* in
    # ``region_names`` is the human-readable name for index *i* in ``zones``.
    # Both lists are sorted by zone ID.
    zones: List[str]  # REGION_RESPONSIBLE_ID values (e.g. ["4", "7A"])
    feature_type: Optional[FeatureType] = None
    gnis_name: Optional[str] = None
    gnis_id: Optional[str] = None
    gnis_name_2: Optional[str] = None
    gnis_id_2: Optional[str] = None
    fwa_watershed_code: Optional[str] = None
    blue_line_key: Optional[str] = None
    mgmt_units: Optional[List[str]] = None
    waterbody_key: Optional[str] = None
    matched_via: Optional[str] = None
    admin_code: Optional[str] = (
        None  # Classification code for admin features (e.g., "PP", "OI")
    )
    region_names: Optional[List[str]] = (
        None  # Paired with zones (e.g. ["Thompson", "Omineca"])
    )

    def __eq__(self, other):
        if not isinstance(other, FWAFeature):
            return False
        return self.fwa_id == other.fwa_id

    def __hash__(self):
        return hash(self.fwa_id)


class FWAUnpickler(pickle.Unpickler):
    """
    Custom unpickler to handle the namespace shift.
    Redirects __main__.FeatureType to our correctly imported FeatureType.
    """

    def find_class(self, module, name):
        if name == "FeatureType" and module == "__main__":
            from fwa_pipeline.metadata_builder import FeatureType

            return FeatureType
        return super().find_class(module, name)


class MetadataGazetteer:
    """
    Gazetteer backed by stream_metadata.pickle file.
    Uses FeatureType Enum members as keys for the internal metadata dictionary.
    """

    def __init__(self, metadata_path: Path):
        """
        Initialize gazetteer from metadata pickle file.
        """
        self.metadata_path = metadata_path
        self.metadata: Dict[Any, Any] = {}
        self.name_index: Dict[str, List[FWAFeature]] = {}
        self._reprojected_admin_cache: Dict[str, Any] = (
            {}
        )  # Cache for reprojected admin layers
        self._fwa_layer_cache: Dict[str, Any] = {}  # Cache for FWA layers with sindex
        self.data_accessor: Optional[FWADataAccessor] = None  # Set via set_gpkg_path()

        self._load_metadata()
        self._build_index()

    def _load_metadata(self):
        """Load metadata from pickle file."""
        logger.info(f"Loading FWA metadata from: {self.metadata_path}")

        with open(self.metadata_path, "rb") as f:
            self.metadata = FWAUnpickler(f).load()

        # Log summary using Enum keys
        logger.info(f"  Zones: {len(self.metadata.get('zone_metadata', {}))}")
        logger.info(f"  Streams: {len(self.metadata.get(FeatureType.STREAM, {})):,}")
        logger.info(f"  Lakes: {len(self.metadata.get(FeatureType.LAKE, {})):,}")
        logger.info(f"  Wetlands: {len(self.metadata.get(FeatureType.WETLAND, {})):,}")
        logger.info(f"  Manmade: {len(self.metadata.get(FeatureType.MANMADE, {})):,}")

        # Admin boundary layers
        for ftype in ADMIN_FEATURE_TYPES:
            count = len(self.metadata.get(ftype, {}))
            if count:
                logger.info(f"  {ftype.name}: {count:,}")

    def _build_feature(
        self,
        fwa_id: str,
        feature_data: Dict[str, Any],
        feature_type: FeatureType,
        matched_via: Optional[str] = None,
    ) -> FWAFeature:
        """Centralized factory for creating FWAFeature objects uniformly."""
        # Admin boundary features use a simplified path
        if feature_type in ADMIN_FEATURE_TYPES:
            gnis_name = feature_data.get("gnis_name")
            if isinstance(gnis_name, str):
                gnis_name = gnis_name.strip() or None
            zones = feature_data.get("zones") or ["Unknown"]
            return FWAFeature(
                fwa_id=str(fwa_id),
                geometry_type="polygon",
                zones=zones,
                feature_type=feature_type,
                gnis_name=gnis_name,
                mgmt_units=feature_data.get("mgmt_units", []),
                admin_code=feature_data.get("admin_code"),
                matched_via=matched_via or f"admin_{feature_type.value}",
                region_names=feature_data.get("region_names", []),
            )

        # Determine geometry type
        geometry_type = (
            "multilinestring" if feature_type == FeatureType.STREAM else "polygon"
        )

        # Determine waterbody_key (polygons fallback to their fwa_id/poly_id if missing)
        waterbody_key = feature_data.get("waterbody_key")
        if waterbody_key is None and feature_type != FeatureType.STREAM:
            waterbody_key = fwa_id

        # Normalize zones
        zones = feature_data.get("zones")
        if not zones:
            zones = ["Unknown"]

        # Safely parse GNIS names
        gnis_name = feature_data.get("gnis_name")
        if isinstance(gnis_name, str):
            gnis_name = gnis_name.strip() or None

        gnis_name_2 = feature_data.get("gnis_name_2")
        if isinstance(gnis_name_2, str):
            gnis_name_2 = gnis_name_2.strip() or None

        # Smart GNIS ID handling: fallback to gnis_id_2 if primary is missing
        gnis_id = feature_data.get("gnis_id")
        gnis_id_2 = feature_data.get("gnis_id_2")
        final_gnis_id = gnis_id if gnis_id else gnis_id_2

        return FWAFeature(
            fwa_id=str(fwa_id),
            geometry_type=geometry_type,
            zones=zones,
            feature_type=feature_type,
            gnis_name=gnis_name,
            gnis_id=final_gnis_id,
            gnis_name_2=gnis_name_2,
            gnis_id_2=gnis_id_2,
            fwa_watershed_code=feature_data.get("fwa_watershed_code"),
            blue_line_key=feature_data.get("blue_line_key"),
            mgmt_units=feature_data.get("mgmt_units", []),
            waterbody_key=str(waterbody_key) if waterbody_key is not None else None,
            matched_via=matched_via,
            region_names=feature_data.get("region_names", []),
        )

    def _build_index(self):
        """Build name-based index from metadata."""
        logger.info("Building name index...")

        # Index streams by gnis_name
        for linear_id, stream_data in self.metadata.get(FeatureType.STREAM, {}).items():
            gnis_name = stream_data.get("gnis_name", "")
            if isinstance(gnis_name, str) and gnis_name.strip():
                feature = self._build_feature(
                    linear_id, stream_data, FeatureType.STREAM
                )
                normalized = self._normalize_for_index(gnis_name)
                self.name_index.setdefault(normalized, []).append(feature)

        # Index lakes, wetlands, manmade by gnis_name and gnis_name_2
        for ftype_enum in [FeatureType.LAKE, FeatureType.WETLAND, FeatureType.MANMADE]:
            for poly_id, feature_data in self.metadata.get(ftype_enum, {}).items():
                gnis_name = feature_data.get("gnis_name", "")
                gnis_name_2 = feature_data.get("gnis_name_2", "")

                if isinstance(gnis_name, str) and gnis_name.strip():
                    feature = self._build_feature(poly_id, feature_data, ftype_enum)
                    normalized = self._normalize_for_index(gnis_name)
                    self.name_index.setdefault(normalized, []).append(feature)

                if isinstance(gnis_name_2, str) and gnis_name_2.strip():
                    feature_2 = self._build_feature(poly_id, feature_data, ftype_enum)
                    normalized_2 = self._normalize_for_index(gnis_name_2)
                    self.name_index.setdefault(normalized_2, []).append(feature_2)

        # Index admin features by name
        for ftype in ADMIN_FEATURE_TYPES:
            for admin_id, admin_data in self.metadata.get(ftype, {}).items():
                gnis_name = admin_data.get("gnis_name", "")
                if isinstance(gnis_name, str) and gnis_name.strip():
                    feature = self._build_feature(admin_id, admin_data, ftype)
                    normalized = self._normalize_for_index(gnis_name)
                    self.name_index.setdefault(normalized, []).append(feature)

        logger.info(f"  Indexed {len(self.name_index):,} unique feature names")

    def _normalize_for_index(self, name: str) -> str:
        """Normalize name for indexing (title case, stripped)."""
        return name.strip().title()

    def search(self, name: str, zone_number: Optional[str] = None) -> List[FWAFeature]:
        """Search for FWA features by name."""
        normalized = self._normalize_for_index(name)
        matches = self.name_index.get(normalized, [])
        if zone_number:
            matches = [f for f in matches if zone_number in f.zones]
        return matches

    def get_stream_metadata(self, linear_feature_id: str) -> Optional[Dict]:
        """Get full metadata dict for a stream."""
        return self.metadata.get(FeatureType.STREAM, {}).get(linear_feature_id)

    def get_valid_stream_ids(self) -> Set[str]:
        """Get set of all valid linear_feature_ids."""
        return set(self.metadata.get(FeatureType.STREAM, {}).keys())

    def get_stream_by_id(self, linear_feature_id: str) -> Optional[FWAFeature]:
        """Get stream feature as FWAFeature by linear_feature_id."""
        metadata = self.get_stream_metadata(linear_feature_id)
        if not metadata:
            return None
        return self._build_feature(linear_feature_id, metadata, FeatureType.STREAM)

    def get_polygon_metadata(
        self, waterbody_key: str, feature_type: Optional[FeatureType] = None
    ) -> Optional[Dict]:
        """Get full metadata for a polygon feature."""
        if feature_type:
            return self.metadata.get(feature_type, {}).get(waterbody_key)

        for ftype in [FeatureType.LAKE, FeatureType.WETLAND, FeatureType.MANMADE]:
            result = self.metadata.get(ftype, {}).get(waterbody_key)
            if result:
                return result
        return None

    def get_zone_metadata(self, zone_number: str) -> Optional[Dict]:
        """Get metadata for a specific zone."""
        return self.metadata.get("zone_metadata", {}).get(zone_number)

    def get_features_in_zone(
        self, zone_number: str, feature_type: FeatureType = FeatureType.STREAM
    ) -> List[Dict]:
        """Get all features in a specific zone."""
        features = []
        for metadata in self.metadata.get(feature_type, {}).values():
            if zone_number in metadata.get("zones", []):
                features.append(metadata)
        return features

    def get_waterbody_by_key(self, waterbody_key: str) -> List[FWAFeature]:
        """Get ALL FWA features with the given waterbody_key."""
        features = []
        for ftype_enum in [FeatureType.LAKE, FeatureType.WETLAND, FeatureType.MANMADE]:
            for poly_id, feature_data in self.metadata.get(ftype_enum, {}).items():
                if str(feature_data.get("waterbody_key", "")) == str(waterbody_key):
                    features.append(
                        self._build_feature(poly_id, feature_data, ftype_enum)
                    )
        return features

    def get_polygon_by_id(self, poly_id: str) -> Optional[FWAFeature]:
        """Get a specific polygon by WATERBODY_POLY_ID."""
        for ftype_enum in [FeatureType.LAKE, FeatureType.WETLAND, FeatureType.MANMADE]:
            feature_data = self.metadata.get(ftype_enum, {}).get(poly_id)
            if feature_data:
                return self._build_feature(poly_id, feature_data, ftype_enum)
        return None

    def search_by_gnis_id(self, gnis_id: str) -> List[FWAFeature]:
        """Search for all features with a specific GNIS ID."""
        features = []
        for lid, meta in self.metadata.get(FeatureType.STREAM, {}).items():
            if str(meta.get("gnis_id")) == str(gnis_id):
                features.append(self.get_stream_by_id(lid))
        for ftype in [FeatureType.LAKE, FeatureType.WETLAND, FeatureType.MANMADE]:
            for fid, meta in self.metadata.get(ftype, {}).items():
                if str(meta.get("gnis_id")) == str(gnis_id):
                    features.append(self.get_polygon_by_id(fid))
        return [f for f in features if f is not None]

    def search_by_watershed_code(self, fwa_watershed_code: str) -> List[FWAFeature]:
        """Search for all stream segments with a specific FWA watershed code."""
        features = []
        for linear_id, metadata in self.metadata.get(FeatureType.STREAM, {}).items():
            if metadata.get("fwa_watershed_code") == fwa_watershed_code:
                features.append(self.get_stream_by_id(linear_id))
        return features

    def search_by_blue_line_key(self, blue_line_key: str) -> List[FWAFeature]:
        """Search for all features (streams AND polygons) with a specific Blue Line Key."""
        features = []
        for lid, meta in self.metadata.get(FeatureType.STREAM, {}).items():
            if str(meta.get("blue_line_key")) == str(blue_line_key):
                features.append(self.get_stream_by_id(lid))
        for ftype in [FeatureType.LAKE, FeatureType.WETLAND, FeatureType.MANMADE]:
            for fid, meta in self.metadata.get(ftype, {}).items():
                if str(meta.get("blue_line_key")) == str(blue_line_key):
                    features.append(self.get_polygon_by_id(fid))
        return [f for f in features if f is not None]

    # --- New Helper Accessors ---

    def get_feature_by_id(self, feature_id: str) -> Optional[FWAFeature]:
        """
        Fetch a single unique feature by its record identifier.
        Supports linear_feature_id (streams) or waterbody_poly_id (polygons).
        """
        # 1. Try stream segment
        stream = self.get_stream_by_id(feature_id)
        if stream:
            return stream

        # 2. Try specific polygon record
        return self.get_polygon_by_id(feature_id)

    def get_feature_by_type_and_id(
        self, ftype: FeatureType, feature_id: str
    ) -> Optional[FWAFeature]:
        """Fetch a feature knowing its type and ID."""
        if ftype == FeatureType.STREAM:
            return self.get_stream_by_id(feature_id)
        # Admin feature types
        if ftype in ADMIN_FEATURE_TYPES:
            return self.get_admin_feature_by_id(ftype, feature_id)
        return self.get_polygon_by_id(feature_id)

    def get_feature_type_from_id(self, feature_id: str) -> FeatureType:
        """Determine feature type from ID by checking existence in metadata collections."""
        if not feature_id:
            return FeatureType.UNKNOWN
        for ftype in [
            FeatureType.STREAM,
            FeatureType.LAKE,
            FeatureType.WETLAND,
            FeatureType.MANMADE,
        ]:
            if feature_id in self.metadata.get(ftype, {}):
                return ftype
        # Check admin types
        for ftype in ADMIN_FEATURE_TYPES:
            if feature_id in self.metadata.get(ftype, {}):
                return ftype
        return FeatureType.UNKNOWN

    # ── Admin Boundary Feature Support ────────────────────────────────────

    def get_admin_feature_by_id(
        self, ftype: FeatureType, admin_id: str
    ) -> Optional[FWAFeature]:
        """Get an admin boundary feature by type and ID from pickle metadata."""
        feature_data = self.metadata.get(ftype, {}).get(str(admin_id))
        if feature_data:
            return self._build_feature(str(admin_id), feature_data, ftype)
        return None

    def set_gpkg_path(self, gpkg_path: Path) -> None:
        """
        Store the GPKG path for on-demand geometry reads (spatial intersection).

        Call this once after construction if spatial operations are needed.
        Admin metadata is already in the pickle; only geometry reads need the GPKG.
        """
        self.gpkg_path = gpkg_path
        self.data_accessor = FWADataAccessor(gpkg_path)
        logger.info(f"GPKG path set for spatial operations: {gpkg_path.name}")

    def search_admin_layer(
        self,
        layer_key: str,
        feature_ids: Optional[List[int]] = None,
        feature_names: Optional[List[str]] = None,
        code_filter: Optional[List[str]] = None,
    ) -> List[FWAFeature]:
        """
        Search an admin boundary layer by ID, name, or classification code.

        Searches the pickle metadata (no GPKG needed).

        Args:
            layer_key: Admin layer key (e.g., 'parks_bc', 'wma')
            feature_ids: Specific feature IDs to match
            feature_names: Name substrings for case-insensitive partial match
            code_filter: Classification codes to pre-filter by (e.g., ['OI'] for
                         ecological reserves in parks_bc).

        Returns:
            List of matched FWAFeature objects (empty list if no matches).
        """
        cfg = ADMIN_LAYER_CONFIG.get(layer_key)
        if not cfg:
            logger.warning(f"Unknown admin layer key: '{layer_key}'")
            return []

        ftype = cfg["feature_type"]
        layer_data = self.metadata.get(ftype, {})
        if not layer_data:
            logger.warning(f"No metadata for admin layer '{layer_key}' ({ftype.name})")
            return []

        # Start with all features in the layer
        candidates = layer_data

        # Pre-filter by classification code
        if code_filter:
            candidates = {
                k: v
                for k, v in candidates.items()
                if v.get("admin_code") in code_filter
            }
            if not candidates:
                logger.warning(
                    f"No features in '{layer_key}' with admin_code in {code_filter}"
                )
                return []

        results = {}

        # Match by feature ID
        if feature_ids:
            missing_ids = []
            for fid in feature_ids:
                fid_str = str(fid)
                if fid_str in candidates:
                    results[fid_str] = candidates[fid_str]
                else:
                    missing_ids.append(fid)

            if missing_ids:
                logger.error(
                    f"Feature IDs not found in '{layer_key}': {missing_ids}. "
                    f"Available IDs: {list(candidates.keys())[:20]}{'...' if len(candidates) > 20 else ''}"
                )
                return []  # Hard fail - all specified IDs must exist

        # Match by name (case-insensitive partial match)
        elif feature_names:
            for admin_id, data in candidates.items():
                name = (data.get("gnis_name") or "").lower()
                for search_name in feature_names:
                    if search_name.lower() in name:
                        results[admin_id] = data
                        break

        # If neither IDs nor names provided, return all candidates
        # This supports provincial regulations that apply to all features in a layer
        # (candidates may be pre-filtered by code_filter if specified)
        else:
            results = candidates

        # Handle empty results
        if not results:
            logger.warning(
                f"No features found in '{layer_key}' for "
                f"ids={feature_ids}, names={feature_names}, code_filter={code_filter}"
            )
            return []

        matched = [
            self._build_feature(aid, adata, ftype) for aid, adata in results.items()
        ]
        names = [f.gnis_name for f in matched if f.gnis_name]
        if len(names) <= 10:
            logger.info(
                f"  Matched {len(matched)} feature(s) in '{layer_key}': {names}"
            )
        else:
            logger.info(
                f"  Matched {len(matched)} feature(s) in '{layer_key}': "
                f"{names[:5]} ... and {len(names) - 5} more"
            )
        return matched

    def get_admin_geometry(
        self,
        layer_key: str,
        admin_features: List[FWAFeature],
        gpkg_path: Optional[Path] = None,
    ) -> Optional[Any]:
        """
        Load polygon geometry from GPKG for the given admin features.

        Args:
            layer_key: Admin layer key (e.g., 'parks_bc')
            admin_features: FWAFeature list from search_admin_layer()
            gpkg_path: Path to GPKG (falls back to self.gpkg_path)

        Returns:
            GeoDataFrame of the matched admin polygons, or None.
        """
        import geopandas as gpd

        gpkg = gpkg_path or getattr(self, "gpkg_path", None)
        if gpkg is None:
            logger.warning("No GPKG path available for geometry read")
            return None

        cfg = ADMIN_LAYER_CONFIG.get(layer_key)
        if not cfg:
            return None

        id_field = cfg["id_field"]
        admin_ids = [str(f.fwa_id) for f in admin_features]

        try:
            # Use cached reprojected layer if available
            cache_key = f"{gpkg}_{layer_key}"
            if cache_key in self._reprojected_admin_cache:
                gdf = self._reprojected_admin_cache[cache_key]
            else:
                # Use FWADataAccessor to ensure consistent normalization
                if self.data_accessor is None:
                    self.data_accessor = FWADataAccessor(gpkg)
                gdf = self.data_accessor.get_layer(layer_key)

                # Reproject to BC Albers (EPSG:3005) to match FWA feature layers
                if gdf.crs and gdf.crs.to_epsg() != 3005:
                    logger.info(
                        f"  Reprojecting '{layer_key}' from {gdf.crs} to EPSG:3005..."
                    )
                    gdf = gdf.to_crs(epsg=3005)

                # Cache the reprojected layer for reuse
                self._reprojected_admin_cache[cache_key] = gdf

            # IDs are already normalized to strings by FWADataAccessor
            matched = gdf[gdf[id_field].isin(admin_ids)]

            if matched.empty:
                # Debug output to show what IDs are available
                available_ids = gdf[id_field].unique()[:20].tolist()
                logger.warning(
                    f"No geometry found in GPKG '{layer_key}' for IDs: {admin_ids}. "
                    f"Sample available IDs: {available_ids}"
                )
                return None
            return matched
        except Exception as e:
            logger.warning(f"Failed to read geometry from '{layer_key}': {e}")
            return None

    def find_features_in_admin_area(
        self,
        admin_features: List[FWAFeature],
        layer_key: str,
        include_streams: bool = True,
        include_lakes: bool = True,
        include_wetlands: bool = False,
        include_manmade: bool = False,
        gpkg_path: Optional[Path] = None,
    ) -> List[FWAFeature]:
        """
        Find all FWA features that spatially intersect with admin boundary polygon(s).

        Uses sindex.query (STRtree R-tree + exact GEOS intersects predicate) for
        a single C-level pass per FWA layer — no Python geometry loops.  FWA layers
        are cached across calls so the expensive GPKG read + sindex build only
        happens once per layer.

        Args:
            admin_features: Admin FWAFeature list from search_admin_layer().
            layer_key: Admin layer key (for geometry lookup in GPKG).
            include_streams: Include stream features.
            include_lakes: Include lake polygon features.
            include_wetlands: Include wetland polygon features.
            include_manmade: Include manmade waterbody features.
            gpkg_path: Path to GPKG for reading layers.

        Returns:
            List of FWAFeature objects that intersect the admin boundary.
        """
        import geopandas as gpd

        gpkg = gpkg_path or getattr(self, "gpkg_path", None)
        if gpkg is None:
            logger.warning("No GPKG path for spatial intersection, returning empty")
            return []

        # Load admin polygon geometry from GPKG
        admin_gdf = self.get_admin_geometry(layer_key, admin_features, gpkg)
        if admin_gdf is None or admin_gdf.empty:
            logger.warning(f"No admin geometry for spatial intersection")
            return []

        features: List[FWAFeature] = []

        # Map of include flags to (layer_name, FeatureType, id_field)
        fwa_layer_map = []
        if include_streams:
            fwa_layer_map.append(("streams", FeatureType.STREAM, "LINEAR_FEATURE_ID"))
        if include_lakes:
            fwa_layer_map.append(("lakes", FeatureType.LAKE, "WATERBODY_POLY_ID"))
        if include_wetlands:
            fwa_layer_map.append(("wetlands", FeatureType.WETLAND, "WATERBODY_POLY_ID"))
        if include_manmade:
            fwa_layer_map.append(
                ("manmade_water", FeatureType.MANMADE, "WATERBODY_POLY_ID")
            )

        # Pre-compute admin union once.
        admin_union = admin_gdf.geometry.union_all()

        # Vertex counts for diagnostics
        def _vcount(g):
            try:
                if hasattr(g, "exterior"):
                    return len(g.exterior.coords)
                return (
                    sum(len(p.exterior.coords) for p in g.geoms)
                    if hasattr(g, "geoms")
                    else 0
                )
            except Exception:
                return -1

        logger.info(f"  Admin polygon: {_vcount(admin_union)} vertices")

        import numpy as np
        import shapely

        PROGRESS_THRESHOLD = 50_000
        CHUNK_SIZE = 50_000

        try:
            from tqdm import tqdm as _tqdm
        except ImportError:
            _tqdm = None

        for layer_name, ftype, id_field in fwa_layer_map:
            try:
                fwa_gdf = self._get_cached_fwa_layer(
                    layer_name, gpkg, id_column=id_field
                )
                if fwa_gdf is None or fwa_gdf.empty:
                    continue

                # Phase 1: bbox-only R-tree query (instant, no GEOS predicate).
                bbox_ilocs = fwa_gdf.sindex.query(admin_union, predicate=None)
                if len(bbox_ilocs) == 0:
                    logger.info(f"  {layer_name}: 0 features in admin bbox")
                    continue

                logger.info(
                    f"  {layer_name}: {len(bbox_ilocs):,} bbox candidates "
                    f"(from {len(fwa_gdf):,} total)"
                )

                # Phase 2: vectorized GEOS intersects — runs entirely in C.
                # Chunked into CHUNK_SIZE batches so tqdm can report between calls.
                candidate_geoms = fwa_gdf.geometry.values[bbox_ilocs]
                candidate_ids = fwa_gdf[id_field].values[bbox_ilocs]
                n = len(candidate_geoms)

                mask_parts = []
                use_progress = _tqdm is not None and n >= PROGRESS_THRESHOLD
                pbar = (
                    _tqdm(total=n, desc=f"    Intersecting {layer_name}", unit="feat")
                    if use_progress
                    else None
                )

                for start in range(0, n, CHUNK_SIZE):
                    end = min(start + CHUNK_SIZE, n)
                    mask_parts.append(
                        shapely.intersects(candidate_geoms[start:end], admin_union)
                    )
                    if pbar:
                        pbar.update(end - start)

                if pbar:
                    pbar.close()

                mask = np.concatenate(mask_parts)
                matched_ids = np.unique(candidate_ids[mask])

                if len(matched_ids) == 0:
                    logger.info(f"  {layer_name}: 0 features intersect admin area")
                    continue

                # Bulk resolve to FWAFeature objects from pickle metadata
                for fwa_id in matched_ids:
                    fwa_id_str = str(fwa_id)
                    if not fwa_id_str:
                        continue

                    existing = self.get_feature_by_type_and_id(ftype, fwa_id_str)
                    if existing:
                        features.append(existing)

                logger.info(
                    f"  {layer_name}: {len(matched_ids)} features intersect admin area"
                )

            except Exception as e:
                logger.warning(f"  Spatial intersection failed for '{layer_name}': {e}")

        logger.info(f"  Total FWA features in admin area: {len(features)}")
        return features

    def _get_cached_fwa_layer(
        self, layer_name: str, gpkg_path: Path, id_column: str = None
    ) -> Optional[Any]:
        """
        Load an FWA layer from GPKG with caching and spatial index.

        Uses FWADataAccessor.get_layer() which normalizes numeric ID columns
        to clean strings (e.g. 169001887.0 → "169001887"), matching the
        pickle metadata keys exactly.

        Only the required id_column + geometry are loaded to minimize memory
        and normalization time (critical for streams with ~5M rows).

        Subsequent calls return the cached GeoDataFrame instantly.
        """
        cache_key = f"{gpkg_path}_{layer_name}"
        if cache_key in self._fwa_layer_cache:
            return self._fwa_layer_cache[cache_key]

        # Use FWADataAccessor for consistent ID normalization (int→str, 0→"")
        if self.data_accessor is None:
            self.data_accessor = FWADataAccessor(gpkg_path)

        if layer_name not in self.data_accessor.list_layers():
            logger.debug(f"  FWA layer '{layer_name}' not in GPKG, skipping")
            self._fwa_layer_cache[cache_key] = None
            return None

        # Only load the ID column we need (+ geometry always included)
        # This avoids normalizing all 15+ columns for 5M stream rows
        columns = [id_column] if id_column else None
        logger.info(
            f"  Loading FWA layer '{layer_name}' via DataAccessor "
            f"(columns={columns or 'ALL'}, first use, will be cached)..."
        )
        try:
            gdf = self.data_accessor.get_layer(layer_name, columns=columns)
            if gdf.empty:
                self._fwa_layer_cache[cache_key] = None
                return None

            # Verify ID normalization worked (should be object/str, not float64)
            if id_column and id_column in gdf.columns:
                dtype = gdf[id_column].dtype
                sample = gdf[id_column].iloc[0] if len(gdf) > 0 else None
                logger.info(
                    f"  ID column '{id_column}' dtype={dtype}, "
                    f"sample={sample!r} (type={type(sample).__name__})"
                )
                if dtype != object:
                    logger.warning(
                        f"  WARNING: '{id_column}' is {dtype}, not object/str! "
                        f"Pickle lookups will FAIL. Check FWADataAccessor normalization."
                    )

            # Ensure EPSG:3005 to match admin geometries
            if gdf.crs and gdf.crs.to_epsg() != 3005:
                logger.debug(
                    f"  Reprojecting FWA '{layer_name}' from {gdf.crs} to EPSG:3005"
                )
                gdf = gdf.to_crs(epsg=3005)

            # Force spatial index build (shapely STRtree)
            _ = gdf.sindex

            self._fwa_layer_cache[cache_key] = gdf
            logger.info(f"  Cached '{layer_name}': {len(gdf)} features with sindex")
            return gdf
        except Exception as e:
            logger.warning(f"  Failed to load FWA layer '{layer_name}': {e}")
            self._fwa_layer_cache[cache_key] = None
            return None
