name = "bc-fishing-r2"
main = "src/index.ts"
compatibility_date = "2024-09-25"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "bc-fishing-regulations"

[vars]
SHARD_VERSION = "v8"

[observability]
[observability.logs]
enabled = false
invocation_logs = true
