// TypeScript mirror of the API.md shapes — the entry is a `CatalogueEntry`
// (pipeline/regs/parsing/catalogue.py). Fields still here from the retired prose model are listed
// under "Not yet ported" in ../../README.md.
// Kept in one file on purpose (throwaway internal tool).

export type Op = "whole" | "upstream_of" | "downstream_of" | "between" | "within";

export type Status =
  | "no_registry"
  | "needs_review"
  | "unused_splits"
  | "unreviewed"
  /** A regional or provincial rule. It names no water BY DEFINITION, so it is a category,
   *  not a problem — it used to show as `no_registry` and sit at the top of the queue. */
  | "zone";

/** Which part of the book an entry came from. `zone` = a region chapter or the provincial
 *  pages; `water` = a row of a water table. They need different questions asked of them. */
export type EntryKind = "zone" | "water";

// ---- Entry model (catalogue.py) -------------------------------------------

export interface Extent {
  op: Op;
  splits: string[];
  item_id?: string | null;
  /** several registry ids, when a reach's two cut-points sit on different waters. Mutually
   *  exclusive with item_id — scoping such a reach to one water puts the other end out of scope. */
  item_ids?: string[];
  area_id?: string | null;
  area_kind?: string | null;
  feature_types?: string[];
}

export interface Rule {
  rule_id: string;
  /** The catalogue TYPE — one of 15, in 6 families. Replaces the retired `restriction_type`,
   *  whose six coarse kinds (closure / harvest / gear_restriction / ...) the model now refuses. */
  type: string;
  /** GENERATED by the backend from type + conditions. Never authored — a label typed beside a
   *  number drifts from it, which is why the hand-written `details` field was removed. */
  label?: string;
  /** The sentence this rule came from: a contiguous quote of the entry's regs_verbatim. */
  verbatim?: string;

  species: string[];
  species_except?: string[];
  /** species a bait/tackle rule is ABOUT ("when fishing for salmon"), distinct from `species`. */
  when_targeting?: string[];

  windows?: string[];
  /** `excepts` marks a window that says when the rule does NOT apply. */
  windows_are?: string;

  take?: number | null;
  unlimited?: boolean;
  period?: string;
  /** take=0 alone is ambiguous: false = may not fish for it, true = fish for it and release it. */
  may_target?: boolean | null;
  water?: string | null;
  record_retention?: boolean;
  obligation?: string;
  standing?: boolean;
  exempts?: unknown;

  extents: Extent[];
  tributaries_only?: boolean;
  /** the reach in the page's own words, when no cut-point can express it. */
  extent_text?: string;
  /** locator phrases nobody could bind; non-empty needs a review_reason. */
  unresolved_locators?: string[];

  review_reason: string;
}

export interface ReviewIssue {
  severity: string;
  problem: string;
  fix: string;
}

export interface ParseReview {
  verdict: string; // "" | pass | changes_requested
  model: string;
  reviewed_at: string;
  issues: ReviewIssue[];
}

export interface Entry {
  entry_id: string;
  /** Flat on a catalogue entry — there is no `identity` block. The MUs the row was printed under
   *  live in `entry_id` after the `@`, which is what keeps the id stable when matching moves. */
  name: string;
  display_name?: string;
  region?: string;
  scope_note?: string;
  includes_tributaries?: boolean | null;
  extents?: Extent[];
  /** Flat on a catalogue entry; the retired prose entry nested these under `source`. */
  source_pages?: number[];
  symbols?: string[];
  regs_verbatim: string;
  matched: string[];
  // NOT CATALOGUE FIELDS — still read by EntryDetail's display, never present on a served entry
  // and refused by the backend if sent. See "Not yet ported" in ../../README.md.
  reference_only?: boolean;
  parse_review?: ParseReview;
  registry_note?: string;
  rules: Rule[];
}

// ---- API response shapes --------------------------------------------------

export interface RegionSummary {
  id: string;
  total: number;
  by_status: Partial<Record<Status, number>>;
}

export interface QueueRow {
  entry_id: string;
  region: string;
  name: string;
  mus: string[];
  status: Status;
  kind?: EntryKind;
  n_rules: number;
  matched_item_id: string | null;
  matched_item_name: string | null;
  also_item_ids: string[]; // a combined override's OTHER items (Chilliwack/Vedder, Fraser + channels)
  unused_curated_splits: number;
}

export interface Boundary {
  id: string;
  label: string;
  kind: string;
  ref: string;
  wbk: string;
  curated: boolean;
  item_id?: string; // which registry item this cut-point belongs to (combined entries)
  meta?: Record<string, unknown> | null; // AS-BUILT split metadata (anchor_type, route_measure, blk, …)
  in_graph?: boolean; // baked into the current graph build
  in_splits?: boolean; // present in the live splits.json source
  live?: { label?: string; kind?: string; anchor?: unknown; note?: string } | null; // live splits.json values
}

export interface SpeciesOption {
  code: string;
  name: string;
  is_group: boolean;
}

export interface SplitRef {
  entry_id: string;
  region: string;
  rule_id: string;
  label: string;
  entry_name: string;
}

export interface Item {
  id: string;
  name: string;
  kind: string;
  variants: string[];
  mus: string[];
  boundaries: Boundary[];
}

export interface MatchInfo {
  item_id: string | null;
  status: string;
  reason: string;
  candidates: unknown[];
  also: string[]; // other registry items a combined override pinned for this row
}

export interface AlsoItem {
  id: string;
  name: string;
  kind: string;
}

/** another synopsis row covering the same water — review it alongside this one */
export interface RelatedEntry {
  entry_id: string;
  region: string;
  name: string;
  n_rules: number;
  /** its regs are just a cross-reference ("See Chilliwack River") */
  pointer: boolean;
  shared_items: { id: string; name: string }[];
}

export interface UnusedSplit {
  id: string;
  label: string;
  anchor_type: string;
}

export interface EntryDetail {
  entry: Entry;
  region: string;
  match: MatchInfo;
  item: Item | null; // `boundaries` is the union over the item AND `also_items`
  also_items: AlsoItem[]; // a combined override's other items — the entry covers these too
  /** Which part of the book this came from — see `EntryKind`. */
  kind?: EntryKind;
  related_entries: RelatedEntry[]; // other synopsis rows over the same water
  unused_curated_splits: UnusedSplit[];
  source_image: string | null; // synopsis row-crop image filename, if found
}

/** One split whose cut lands at more than one measure on the same blue line, so the reach shown is
 *  one of two honest readings (an area boundary the stream crosses twice). */
export interface AmbiguousCut {
  split_id: string;
  used: number;
  also_at: number[];
}

/** What one extent actually selects on the map. `unclassified` = pieces that genuinely straddle the
 *  reach's end, surfaced rather than silently included or dropped. */
export interface ResolvedExtent {
  sections: string[];
  unclassified: string[];
  ambiguous_cut: AmbiguousCut[];
  /** the named waters this reach actually lands on, biggest share first */
  waters: string[];
}

/** A distinct reach within one entry, shared by every rule that resolves to the same sections.
 *  `key` is a short stable label (A, B, C…) so the rules list and the map agree on what to call it. */
export interface ReachIdentity {
  key: string;
  color: string;
  waters: string[];
  n: number;
}

/** GET /api/entries/{id}/reaches — per rule, one entry per extent (null = not determinable). */
export interface EntryReaches {
  covered: string[];
  rules: Record<string, (ResolvedExtent | null)[]>;
  /** the BUILDER's answer per rule — outcome + the sections that actually ship, tributaries
   *  already expanded. `rules` above is the raw per-extent resolve and has no tributaries. */
  verdict?: Record<string, RuleVerdict>;
}

export interface RuleVerdict {
  outcome: string;
  reason: string | null;
  detail: string;
  n_sections: number;
  sections: string[];
  tributaries_pending: boolean;
  diagnostics: { kind: string; [k: string]: unknown }[];
}

/** One EXCEPT clause and what it removed. `above` is everything upstream of the named water,
 *  which a carve-out always takes with it. */
export interface CarveOut {
  extent: unknown;
  resolved: boolean;
  n_sections: number;
  above: number;
}

/** What one rule resolves to: IN (`sections`) and OUT (`n_excluded` + the drawn exclusions). */
export interface RuleResolved {
  entry_id: string;
  rule_id: string;
  outcome: string;
  wants_tributaries: boolean;
  tributaries_only: boolean;
  within_area: boolean;
  /** how many EXCEPT carve-outs the entry/rule authors */
  n_carve_outs_authored: number;
  /** ...and whether they bite on THIS rule. They only apply where tributaries are expanded,
   *  so a mainstem-only rule authors them but is not narrowed by them. */
  carve_outs_apply: boolean;
  /** the extents alone, before tributary/area expansion */
  n_direct: number;
  /** what the builder ADDED — tributaries, or an area's other waters */
  n_added: number;
  n_total: number;
  /** sections the EXCEPT carve-outs removed */
  n_excluded: number;
  /** bound sections the item layer never had, so they exist only in this payload */
  n_offitem: number;
  carve_outs: CarveOut[];
  sections: string[];
  truncated: boolean;
  limit: number;
  geojson: GeoJSON;
  error?: string;
}

export interface ItemSearchResult {
  id: string;
  name: string;
  kind: string;
  mus: string[];
}

export interface SaveResult {
  ok: boolean;
  errors: string[];
}

export interface GeoJSON {
  type: string;
  features: unknown[];
  _todo?: string;
}

// ---- Graph rebuild (pipeline.atlas.build --full, run as a background subprocess) ----

export interface RebuildStage {
  label: string;
  done: boolean;
  seconds: number | null;
}

export interface RebuildStatus {
  status: "idle" | "running" | "done" | "error";
  elapsed_s: number;
  current: string;
  stages: RebuildStage[];
  n_done: number;
  n_total: number;
  returncode: number | null;
  error: string;
  log_tail: string[];
}
