"""
Two-layer regulation table for pipeline.

Architecture
------------
Every synopsis row maps to exactly one entry.  There are two layers:

    BaseEntry    — auto-generated by running the v2 linker on
                   synopsis_raw_data.json.  Contains only gnis_ids — the
                   stable identifier from natural name search.  Everything
                   else (geometry, edge_ids, poly_ids) is resolved at
                   runtime from gnis_id by downstream pipeline steps.

    OverrideEntry — manually authored corrections (source of truth:
                    overrides.json).  An OverrideEntry for a given
                    (region, name_verbatim) always wins over a BaseEntry.
                    Can use gnis_ids, waterbody_keys, fwa_watershed_codes,
                    or admin_targets as identifiers.

Both layers inherit from _EntryBase which provides common fields:
    criteria (MatchCriteria), gnis_ids, name_variants.

All ``fwa_watershed_codes`` are normalised via ``trim_wsc()`` on load
so padded values in overrides.json match trimmed atlas records.

Lookup key
----------
Index key is (region, name_verbatim, frozenset(mus)).  All three fields
must match exactly — when a synopsis row changes its MUs, the match breaks
visibly instead of silently returning a stale entry.

Name variants
-------------
One entry can cover multiple synopsis names via name_variants.  Each variant
shares the same region as the primary criteria.  Both the primary name and all
variants are indexed so lookup always returns the same entry regardless of
which name appears in the synopsis row.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

from pipeline.utils.wsc import trim_wsc

from .reg_models import MatchCriteria

# Canonical paths for curated data files (live next to code)
_PACKAGE_DIR = Path(__file__).resolve().parent
OVERRIDES_PATH = _PACKAGE_DIR / "overrides.json"
FEATURE_DISPLAY_NAMES_PATH = _PACKAGE_DIR / "feature_display_names.json"


# ---------------------------------------------------------------------------
# Entry types
# ---------------------------------------------------------------------------


@dataclass
class _EntryBase:
    """Shared fields for all match table entries.

    gnis_ids is the primary FWA identifier — the natural search finds
    features by GNIS name and returns their GNIS IDs.  Geometry, edge_ids,
    poly_ids, and zones are resolved at runtime from gnis_id by downstream
    pipeline steps.

    NOTE: All subclass fields must have defaults because gnis_ids and
    name_variants already have defaults.  Adding a required field to a
    subclass will raise TypeError at class creation time.
    """

    criteria: MatchCriteria
    gnis_ids: List[str] = field(default_factory=list)
    name_variants: List[str] = field(default_factory=list)

    @property
    def has_match(self) -> bool:
        """True if this entry resolved to at least one FWA feature."""
        return bool(self.gnis_ids)

    @property
    def match_type(self) -> str:
        """Provenance classification: 'direct', 'admin', or 'unmatched'."""
        return "direct" if self.gnis_ids else "unmatched"


@dataclass
class BaseEntry(_EntryBase):
    """Auto-generated from natural gazetteer search.

    Produced by running BaseEntryBuilder.build_table() on synopsis_raw_data.json.
    Empty gnis_ids means the natural search found nothing — the entry still
    exists so the absence is visible rather than silently omitted.

    link_method is an audit string ("natural_search", "not_found", etc.).
    """

    link_method: str = "natural_search"

    def to_dict(self) -> Dict[str, Any]:
        return {
            "type": "base",
            "criteria": {
                "name_verbatim": self.criteria.name_verbatim,
                "region": self.criteria.region,
                "mus": self.criteria.mus,
            },
            "gnis_ids": self.gnis_ids,
            "name_variants": self.name_variants,
            "link_method": self.link_method,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "BaseEntry":
        c = data["criteria"]
        # Backward compat: extract gnis_ids from old fwa_refs format
        gnis_ids = data.get("gnis_ids", [])
        if not gnis_ids and "fwa_refs" in data:
            seen: set = set()
            for ref in data["fwa_refs"]:
                for key in ("gnis_id", "gnis_id_2"):
                    gid = ref.get(key, "")
                    if gid and gid not in seen:
                        seen.add(gid)
                        gnis_ids.append(gid)
        return cls(
            criteria=MatchCriteria(
                name_verbatim=c["name_verbatim"],
                region=c.get("region"),
                mus=c.get("mus", []),
            ),
            gnis_ids=gnis_ids,
            name_variants=data.get("name_variants", []),
            link_method=data.get("link_method", "natural_search"),
        )


@dataclass
class OverrideEntry(_EntryBase):
    """Manually authored correction — always wins over a BaseEntry.

    Source of truth: overrides.json (validated JSON, loaded via from_dict).
    Replaces v1 linking_corrections.py DIRECT_MATCHES / SKIP_ENTRIES /
    NAME_VARIATION_LINKS / ADMIN_DIRECT_MATCHES tables.

    Identifier priority (use the most stable available):
        gnis_ids            — best for most lakes and named streams
        waterbody_keys      — unnamed polygons, multi-polygon waterbodies
        fwa_watershed_codes — streams identified only by watershed code
        blue_line_keys      — specific stream segments (e.g., side channels)
        linear_feature_ids  — individual FWA edge segments
        waterbody_poly_ids  — specific polygon features

    Admin matching:
        admin_targets       — polygon identity only; spatial intersection
                              with FWA features happens in a downstream step.
        admin_feature_types — optional restriction on which FWA types to
                              include (e.g. ["LAKE"] for park lake-only regs).

    Custom geometry:
        ungazetted_waterbody_id — references a custom waterbody not in FWA.

    skip = True  → intentionally skipped (name variant / cross-listing).
    additional_info  → injected as a 'Note' rule on the front end.
    """

    note: str = ""
    # Additional identifier types beyond gnis_ids (inherited from _EntryBase)
    waterbody_keys: List[str] = field(default_factory=list)
    fwa_watershed_codes: List[str] = field(default_factory=list)
    blue_line_keys: List[str] = field(default_factory=list)
    linear_feature_ids: List[str] = field(default_factory=list)
    waterbody_poly_ids: List[str] = field(default_factory=list)
    ungazetted_waterbody_id: Optional[str] = None
    ungazetted_location: Optional[List[float]] = None  # [lon, lat] WGS84
    # Admin polygon targets: [{"layer": "parks_bc", "feature_id": "1125"}, ...]
    admin_targets: List[Dict[str, str]] = field(default_factory=list)
    admin_feature_types: Optional[List[str]] = None
    canonical_name: str = ""
    skip: bool = False
    skip_reason: Optional[str] = None
    variant_of: Optional[MatchCriteria] = None
    additional_info: Optional[str] = None

    @property
    def has_match(self) -> bool:
        """True if this entry resolved to at least one FWA feature or admin area."""
        if self.skip:
            return False
        return bool(
            self.gnis_ids
            or self.waterbody_keys
            or self.fwa_watershed_codes
            or self.blue_line_keys
            or self.linear_feature_ids
            or self.waterbody_poly_ids
            or self.ungazetted_waterbody_id
            or self.admin_targets
        )

    @property
    def _has_direct_ids(self) -> bool:
        """True if the entry has any direct feature identifier."""
        return bool(
            self.gnis_ids
            or self.waterbody_keys
            or self.fwa_watershed_codes
            or self.blue_line_keys
            or self.linear_feature_ids
            or self.waterbody_poly_ids
            or self.ungazetted_waterbody_id
        )

    @property
    def match_type(self) -> str:
        """Provenance classification: 'direct', 'admin', or 'unmatched'."""
        if self.skip:
            return "unmatched"
        if self._has_direct_ids:
            return "direct"
        if self.admin_targets:
            return "admin"
        return "unmatched"

    def to_dict(self) -> Dict[str, Any]:
        d: Dict[str, Any] = {
            "type": "override",
            "criteria": {
                "name_verbatim": self.criteria.name_verbatim,
                "region": self.criteria.region,
                "mus": self.criteria.mus,
            },
            "note": self.note,
        }
        # Only include non-empty / non-default fields
        if self.gnis_ids:
            d["gnis_ids"] = self.gnis_ids
        if self.waterbody_keys:
            d["waterbody_keys"] = self.waterbody_keys
        if self.fwa_watershed_codes:
            d["fwa_watershed_codes"] = self.fwa_watershed_codes
        if self.blue_line_keys:
            d["blue_line_keys"] = self.blue_line_keys
        if self.linear_feature_ids:
            d["linear_feature_ids"] = self.linear_feature_ids
        if self.waterbody_poly_ids:
            d["waterbody_poly_ids"] = self.waterbody_poly_ids
        if self.ungazetted_waterbody_id is not None:
            d["ungazetted_waterbody_id"] = self.ungazetted_waterbody_id
        if self.ungazetted_location is not None:
            d["ungazetted_location"] = self.ungazetted_location
        if self.admin_targets:
            d["admin_targets"] = self.admin_targets
        if self.admin_feature_types is not None:
            d["admin_feature_types"] = self.admin_feature_types
        if self.name_variants:
            d["name_variants"] = self.name_variants
        if self.canonical_name:
            d["canonical_name"] = self.canonical_name
        if self.skip:
            d["skip"] = self.skip
        if self.skip_reason is not None:
            d["skip_reason"] = self.skip_reason
        if self.variant_of is not None:
            d["variant_of"] = {
                "name_verbatim": self.variant_of.name_verbatim,
                "region": self.variant_of.region,
                "mus": self.variant_of.mus,
            }
        if self.additional_info is not None:
            d["additional_info"] = self.additional_info
        return d

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "OverrideEntry":
        c = data["criteria"]
        # Backward compat: extract gnis_ids from old fwa_refs format
        gnis_ids = data.get("gnis_ids", [])
        if not gnis_ids and "fwa_refs" in data:
            seen: set = set()
            for ref in data["fwa_refs"]:
                for key in ("gnis_id", "gnis_id_2"):
                    gid = ref.get(key, "")
                    if gid and gid not in seen:
                        seen.add(gid)
                        gnis_ids.append(gid)
        return cls(
            criteria=MatchCriteria(
                name_verbatim=c["name_verbatim"],
                region=c.get("region"),
                mus=c.get("mus", []),
            ),
            note=data.get("note", ""),
            gnis_ids=gnis_ids,
            waterbody_keys=data.get("waterbody_keys", []),
            fwa_watershed_codes=[
                trim_wsc(w) for w in data.get("fwa_watershed_codes", [])
            ],
            blue_line_keys=data.get("blue_line_keys", []),
            linear_feature_ids=data.get("linear_feature_ids", []),
            waterbody_poly_ids=data.get("waterbody_poly_ids", []),
            ungazetted_waterbody_id=data.get("ungazetted_waterbody_id"),
            ungazetted_location=data.get("ungazetted_location"),
            admin_targets=data.get("admin_targets", []),
            admin_feature_types=data.get("admin_feature_types"),
            name_variants=data.get("name_variants", []),
            canonical_name=data.get("canonical_name", ""),
            skip=data.get("skip", False),
            skip_reason=data.get("skip_reason"),
            variant_of=(
                MatchCriteria(
                    name_verbatim=data["variant_of"]["name_verbatim"],
                    region=data["variant_of"].get("region"),
                    mus=data["variant_of"].get("mus", []),
                )
                if data.get("variant_of")
                else None
            ),
            additional_info=data.get("additional_info"),
        )


@dataclass
class FeatureDisplayName:
    """Display name override for specific FWA features identified by BLK/WBK.

    Used for unnamed features (e.g., side channels) that need their own
    display name and search grouping on the front end.  Applied at the
    merge/export step, not during matching.

    At least one of blue_line_keys or waterbody_keys must be provided.
    """

    display_name: str
    note: str = ""
    blue_line_keys: List[str] = field(default_factory=list)
    waterbody_keys: List[str] = field(default_factory=list)

    def __post_init__(self) -> None:
        if not self.blue_line_keys and not self.waterbody_keys:
            raise ValueError(
                "FeatureDisplayName requires at least one of "
                "blue_line_keys or waterbody_keys"
            )

    def to_dict(self) -> Dict[str, Any]:
        d: Dict[str, Any] = {"display_name": self.display_name, "note": self.note}
        if self.blue_line_keys:
            d["blue_line_keys"] = self.blue_line_keys
        if self.waterbody_keys:
            d["waterbody_keys"] = self.waterbody_keys
        return d

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "FeatureDisplayName":
        return cls(
            display_name=data["display_name"],
            note=data.get("note", ""),
            blue_line_keys=data.get("blue_line_keys", []),
            waterbody_keys=data.get("waterbody_keys", []),
        )


# ---------------------------------------------------------------------------
# Lookup engine
# ---------------------------------------------------------------------------

AnyEntry = Union[BaseEntry, OverrideEntry]


class MatchTable:
    """Merge base entries and overrides into one lookup index.

    Index key is (region, name_verbatim, frozenset(mus)).
    Override always wins over a base entry for the same key.
    Both primary names and name_variants are indexed.

    Lookup is fully qualified — all three fields must match exactly.
    When a synopsis row changes its MUs, the match breaks visibly instead of
    silently returning the stale entry.

    Usage
    -----
        table = MatchTable(bases, overrides)
        entry = table.lookup("ELK RIVER", "Region 3", ["3-5", "3-6"])
        # entry is OverrideEntry if one exists, otherwise BaseEntry, or None.
    """

    def __init__(
        self,
        bases: List[BaseEntry],
        overrides: List[OverrideEntry],
    ) -> None:
        # Index overrides first — they have priority.
        self._idx: Dict[tuple, AnyEntry] = {}

        for entry in overrides:
            self._index(entry)

        # Base entries fill gaps left by overrides.
        for entry in bases:
            key = self._make_key(
                entry.criteria.region,
                entry.criteria.name_verbatim,
                entry.criteria.mus,
            )
            if key not in self._idx:
                self._index(entry)

        # Propagate variant_of: skipped entries contribute their
        # name_verbatim as a name_variant on the target entry.
        self._propagate_variant_of(overrides)

    # ------------------------------------------------------------------

    _logger = logging.getLogger(__name__)

    def _propagate_variant_of(self, overrides: List[OverrideEntry]) -> None:
        """Add each skip entry's name as a name_variant on the target entry.

        variant_of is a full MatchCriteria pointing to an exact entry via
        the same (region, name_verbatim, mus) lookup key the index uses.
        """
        for ov in overrides:
            if not ov.variant_of:
                continue
            target = self.lookup(
                ov.variant_of.name_verbatim,
                ov.variant_of.region,
                ov.variant_of.mus,
            )
            if target is None:
                self._logger.warning(
                    "variant_of %r on %r did not resolve to any entry",
                    ov.variant_of.name_verbatim,
                    ov.criteria.name_verbatim,
                )
                continue
            variant_name = ov.criteria.name_verbatim
            if variant_name not in target.name_variants:
                target.name_variants.append(variant_name)

    @staticmethod
    def _make_key(
        region: Optional[str],
        name_verbatim: str,
        mus: List[str],
    ) -> tuple:
        """Stable, hashable index key including all three match dimensions."""
        return (region, name_verbatim, frozenset(mus))

    def _index(self, entry: AnyEntry) -> None:
        """Add an entry (and all its name variants) to the index."""
        key = self._make_key(
            entry.criteria.region,
            entry.criteria.name_verbatim,
            entry.criteria.mus,
        )
        self._idx[key] = entry
        for variant in entry.name_variants:
            vkey = self._make_key(entry.criteria.region, variant, entry.criteria.mus)
            # Don't overwrite an existing override with a variant reference.
            if vkey not in self._idx:
                self._idx[vkey] = entry

    def lookup(
        self,
        name_verbatim: str,
        region: Optional[str],
        mus: Optional[List[str]] = None,
        *,
        ignore_mus: bool = False,
    ) -> Optional[AnyEntry]:
        """Return the entry for (region, name_verbatim, mus), or None.

        mus must match exactly (same set of MU codes as stored in the entry).
        If you pass mus=None the key is built with an empty MU set, which only
        matches entries that were also stored with no MUs.

        When *ignore_mus* is True (used by in-season resolution where MUs
        are unknown), tries exact first, then scans for any entry matching
        (region, name_verbatim) regardless of MU set.
        """
        exact = self._idx.get(self._make_key(region, name_verbatim, mus or []))
        if exact is not None or not ignore_mus:
            return exact
        # Fallback: scan for any entry with same (region, name) case-insensitively
        name_upper = name_verbatim.upper()
        for (r, n, _mu_set), entry in self._idx.items():
            if r == region and n.upper() == name_upper:
                return entry
        return None

    def all_entries(self) -> List[AnyEntry]:
        """Return all unique entries (de-duplicated across variant keys)."""
        seen: set = set()
        result: List[AnyEntry] = []
        for entry in self._idx.values():
            eid = id(entry)
            if eid not in seen:
                seen.add(eid)
                result.append(entry)
        return result
